import os
import csv
import json
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT, 'Data', 'OnePiece')
OUTPUT_FILE = os.path.join(ROOT, 'database', '050_final_reseed.sql')

# Name normalization for matching
def normalize_name(name):
    if not name: return ""
    # Remove titles, brackets, etc.
    name = re.sub(r'\(.*?\)', '', name)
    name = re.sub(r'\[.*?\]', '', name)
    name = re.sub(r'\†', '', name)
    name = name.split(';')[0].strip()
    return name.lower().replace(' ', '').replace('-', '').replace('.', '').replace('\'', '')

def escape_sql(val):
    if val is None or str(val).lower() == 'null' or str(val).lower() == 'nan' or str(val).lower() == 'na':
        return 'NULL'
    if isinstance(val, bool):
        return 'TRUE' if val else 'FALSE'
    if isinstance(val, str):
        # Escape single quotes
        return "'" + val.replace("'", "''") + "'"
    return str(val)

def parse_num(val):
    if not val or str(val).lower() in ['null', 'nan', 'na']:
        return 'NULL'
    clean = re.sub(r'[^0-9.]', '', str(val))
    return clean if clean else 'NULL'

def parse_bounty_val(b_str):
    if not b_str: return 0
    # Take only the first part before parenthesis or significant separators if needed
    # But usually the first continuous number is the current bounty.
    first_part = str(b_str).split('(')[0].split(';')[0].split(',')[0].strip()
    # Actually, if the string is "1,111,000,000 (previously...)", we want the first part.
    # Let's use regex to find the first sequence of numbers/commas/dots and clean it.
    match = re.search(r'([0-9,.]+)', str(b_str))
    if match:
        clean = re.sub(r'[^0-9]', '', match.group(1))
        try:
            return int(clean) if clean else 0
        except:
            return 0
    return 0

def run_ultimate_reseed():
    sql_lines = []
    sql_lines.append("-- ULTIMATE ONE PIECE DATABASE RESEED")
    sql_lines.append("-- Generated by Reseed Ultimate Script")
    sql_lines.append("BEGIN;")
    
    # ID Mapping for Linking
    char_name_map = {} # normalized_name -> character_id_mal to link Haki/Bounties
    faction_name_map = {} # normalized_name -> faction_id sql
    arc_name_map = {} # normalized_name -> arc_id sql

    # --- 1. ARCS ---
    sql_lines.append("\n-- 1. Arcs")
    arcs_path = os.path.join(DATA_DIR, 'OnePieceArcs', 'OnePieceArcs.csv')
    if os.path.exists(arcs_path):
        with open(arcs_path, 'r', encoding='utf-8', errors='replace') as f:
            reader = csv.DictReader(f)
            for row in reader:
                a_name = row['Arc']
                sql = f"""INSERT INTO op_arcs (arc_name, saga, start_chapter, total_chapters, start_episode, total_episodes) VALUES (
                    {escape_sql(a_name)}, {escape_sql(row.get('Saga', 'One Piece'))}, {parse_num(row.get('Start onChapter'))}, {parse_num(row.get('TotalChapters'))}, {parse_num(row.get('Start onEpisode'))}, {parse_num(row.get('TotalEpisodes'))}
                ) ON CONFLICT (arc_name) DO UPDATE SET saga = EXCLUDED.saga RETURNING id;"""
                sql_lines.append(sql)
                arc_name_map[normalize_name(a_name)] = f"(SELECT id FROM op_arcs WHERE arc_name = {escape_sql(a_name)})"

    # --- 2. FACTIONS ---
    sql_lines.append("\n-- 2. Factions")
    factions_path = os.path.join(DATA_DIR, 'op_factions.csv')
    if os.path.exists(factions_path):
        with open(factions_path, 'r', encoding='utf-8', errors='replace') as f:
            reader = csv.DictReader(f)
            for row in reader:
                f_name = row['name']
                sql = f"""INSERT INTO op_factions (name, name_japanese, type, leader_name, ship_name, total_bounty, status, base_location, description) VALUES (
                    {escape_sql(f_name)}, {escape_sql(row.get('name_japanese'))}, {escape_sql(row.get('type'))}, {escape_sql(row.get('leader_name'))}, {escape_sql(row.get('ship_name'))}, {parse_bounty_val(row.get('total_bounty'))}, {escape_sql(row.get('status'))}, {escape_sql(row.get('base_location'))}, {escape_sql(row.get('description'))}
                ) ON CONFLICT (name) DO NOTHING;"""
                sql_lines.append(sql)
                faction_name_map[normalize_name(f_name)] = f"(SELECT id FROM op_factions WHERE name = {escape_sql(f_name)})"

    # --- 3. DEVIL FRUITS (Extracted later from characters) ---
    fruits_found = set()

    # --- 4. CHARACTERS ---
    sql_lines.append("\n-- 4. Characters")
    chars_csv = os.path.join(DATA_DIR, 'One_Piece.csv')
    image_base_dir = os.path.join(DATA_DIR, 'Characters')
    
    if os.path.exists(chars_csv):
        with open(chars_csv, 'r', encoding='utf-8', errors='replace') as f:
            reader = csv.DictReader(f)
            for row in reader:
                mal_id = row['character_id']
                full_name = row['full_name']
                desc = row['description']
                
                # Attribute parsing
                attrs = {}
                try:
                    attr_list = json.loads(row['attributes'])
                    attrs = {a['name']: a['value'] for a in attr_list}
                except: pass
                
                # Extract fields
                epithet = attrs.get('Epithet', '') or attrs.get('Alias', '')
                status = attrs.get('Status', 'Active')
                age = attrs.get('Age', '')
                height = attrs.get('Height', '')
                birthday = attrs.get('Birthdate', attrs.get('Birthday', ''))
                blood_type = attrs.get('Blood type', '')
                n_kanji = attrs.get('Japanese name', '')
                origin = attrs.get('Origin', '')
                residence = attrs.get('Residence', '')
                occupation = attrs.get('Occupation', attrs.get('Position', ''))
                bounty_str = attrs.get('Bounty', '0')
                bounty_val = parse_bounty_val(bounty_str)
                
                # Faction Link
                affiliation = attrs.get('Affiliation', '')
                f_id_sql = 'NULL'
                if affiliation:
                    for f_norm, f_sql in faction_name_map.items():
                        if f_norm in normalize_name(affiliation):
                            f_id_sql = f_sql
                            break

                # Devil Fruit Link
                df_name = attrs.get('Devil fruit', attrs.get('Devil Fruit', ''))
                df_id_sql = 'NULL'
                if df_name and df_name.lower() != 'none':
                    # Split if multiple fruits (like Luffy or Blackbeard)
                    for single_fruit in df_name.split(','):
                        clean_fruit = single_fruit.strip()
                        if clean_fruit and clean_fruit not in fruits_found:
                            fsql = f"INSERT INTO op_devil_fruits (name, type) VALUES ({escape_sql(clean_fruit)}, {escape_sql(attrs.get('Type'))}) ON CONFLICT (name) DO NOTHING;"
                            sql_lines.append(fsql)
                            fruits_found.add(clean_fruit)
                    # For the link, just take the first one or the whole string if preferred.
                    # Usually characters have one.
                    first_fruit = df_name.split(',')[0].strip()
                    df_id_sql = f"(SELECT id FROM op_devil_fruits WHERE name = {escape_sql(first_fruit)})"

                # Image Mapping
                folder_matches = []
                if os.path.exists(image_base_dir):
                    dirs = [d for d in os.listdir(image_base_dir) if os.path.isdir(os.path.join(image_base_dir, d))]
                    norm_full = normalize_name(full_name)
                    for d in dirs:
                        norm_d = normalize_name(d)
                        if norm_d == norm_full or norm_d in norm_full or norm_full in norm_d:
                            folder_matches.append(d)
                
                final_folder = folder_matches[0] if folder_matches else None
                image_url = f"characters/{final_folder}/primary.jpg" if final_folder else None
                
                # Gallery
                gallery = []
                if final_folder:
                    fpath = os.path.join(image_base_dir, final_folder)
                    if os.path.exists(fpath):
                        for file in os.listdir(fpath):
                            if file.lower().endswith(('.jpg', '.png', '.webp', '.jpeg')):
                                gallery.append(f"characters/{final_folder}/{file}")

                sql = f"""INSERT INTO op_characters (
                    character_id_mal, name, name_kanji, about, image_folder, image_url, gallery_images,
                    devil_fruit_id, faction_id, position, epithet, origin, residence, occupation, status,
                    birthday, blood_type, height, age, bounty, bounty_formatted
                ) VALUES (
                    {escape_sql(mal_id)}, {escape_sql(full_name)}, {escape_sql(n_kanji)}, {escape_sql(desc)}, 
                    {escape_sql(final_folder)}, {escape_sql(image_url)}, {escape_sql(json.dumps(gallery))},
                    {df_id_sql}, {f_id_sql}, {escape_sql(occupation)}, {escape_sql(epithet)}, 
                    {escape_sql(origin)}, {escape_sql(residence)}, {escape_sql(occupation)}, {escape_sql(status)},
                    {escape_sql(birthday)}, {escape_sql(blood_type)}, {escape_sql(height)}, {escape_sql(age)},
                    {bounty_val}, {escape_sql(bounty_str)}
                ) ON CONFLICT (character_id_mal) DO UPDATE SET bounty = EXCLUDED.bounty, about = EXCLUDED.about, image_folder = EXCLUDED.image_folder;"""
                sql_lines.append(sql)
                char_name_map[normalize_name(full_name)] = mal_id

    # --- 5. EPISODES ---
    sql_lines.append("\n-- 5. Episodes")
    ep_path = os.path.join(DATA_DIR, 'One Piece json.json')
    if os.path.exists(ep_path):
        with open(ep_path, 'r', encoding='utf-8') as f:
            ep_data = json.load(f)
            for ep in ep_data:
                ep_num = ep.get('episode')
                if not ep_num: continue
                air_date = str(ep.get('start')) if ep.get('start') else None
                sql = f"""INSERT INTO op_episodes (episode_number, title, air_date, rating, total_votes, summary) VALUES (
                    {ep_num}, {escape_sql(ep.get('name'))}, {escape_sql(air_date)}, {parse_num(ep.get('average_rating'))}, {parse_num(ep.get('total_votes'))}, {escape_sql(ep.get('description'))}
                ) ON CONFLICT (episode_number) DO NOTHING;"""
                sql_lines.append(sql)

    # --- 6. CHAPTERS ---
    sql_lines.append("\n-- 6. Chapters")
    chap_path = os.path.join(DATA_DIR, 'Chapters.csv')
    if os.path.exists(chap_path):
        with open(chap_path, 'r', encoding='utf-8', errors='replace') as f:
            reader = csv.DictReader(f)
            for row in reader:
                c_num = row.get('Chapter_Number')
                if not c_num: continue
                # Ensure date is quoted
                release_date = str(row.get('Date')) if row.get('Date') else None
                sql = f"""INSERT INTO op_chapters (chapter_number, title, viz_title, pages, release_date) VALUES (
                    {c_num}, {escape_sql(row.get('Name'))}, {escape_sql(row.get('Viz_title'))}, {parse_num(row.get('Pages'))}, {escape_sql(release_date)}
                ) ON CONFLICT (chapter_number) DO NOTHING;"""
                sql_lines.append(sql)

    # --- 7. HAKI USERS ---
    sql_lines.append("\n-- 7. Haki Users")
    haki_path = os.path.join(DATA_DIR, 'HakiUsers', 'haki_users.csv')
    if os.path.exists(haki_path):
        with open(haki_path, 'r', encoding='utf-8', errors='replace') as f:
            reader = csv.DictReader(f)
            for row in reader:
                c_name = row['character']
                n_c_name = normalize_name(c_name)
                mal_id = char_name_map.get(n_c_name)
                
                if mal_id:
                    c_id_sql = f"(SELECT id FROM op_characters WHERE character_id_mal = {escape_sql(mal_id)})"
                    sql = f"""INSERT INTO op_haki_users (character_id, character_name, observation_haki, armament_haki, conquerors_haki) VALUES (
                        {c_id_sql}, {escape_sql(c_name)}, {escape_sql(row.get('Observation') == '1')}, {escape_sql(row.get('Armament') == '1')}, {escape_sql(row.get("Conqueror's") == '1')}
                    ) ON CONFLICT (character_id) DO NOTHING;"""
                    sql_lines.append(sql)

    # --- 8. BOUNTIES ---
    sql_lines.append("\n-- 8. Bounties")
    bounties_path = os.path.join(DATA_DIR, 'op_bounties.csv')
    if not os.path.exists(bounties_path):
         bounties_path = os.path.join(DATA_DIR, 'bounties.csv')
         
    if os.path.exists(bounties_path):
        with open(bounties_path, 'r', encoding='utf-8', errors='replace') as f:
            reader = csv.DictReader(f)
            for row in reader:
                c_name = row['character_name']
                n_c_name = normalize_name(c_name)
                mal_id = char_name_map.get(n_c_name) or row.get('character_id')
                
                if mal_id:
                    c_id_sql = f"(SELECT id FROM op_characters WHERE character_id_mal = {escape_sql(mal_id)})"
                    sql = f"""INSERT INTO op_bounties (character_id, character_name, amount, arc_revealed, chapter_revealed, is_current, reason) VALUES (
                        {c_id_sql}, {escape_sql(c_name)}, {parse_bounty_val(row.get('bounty_amount'))}, {escape_sql(row.get('arc_revealed'))}, {parse_num(row.get('chapter_revealed'))}, {row.get('bounty_status') == 'Active'}, {escape_sql(row.get('reason_for_bounty'))}
                    ) ON CONFLICT DO NOTHING;"""
                    sql_lines.append(sql)

    # --- 9. SHIPS ---
    sql_lines.append("\n-- 9. Ships")
    ships_path = os.path.join(DATA_DIR, 'op_ships.csv')
    if os.path.exists(ships_path):
        with open(ships_path, 'r', encoding='utf-8', errors='replace') as f:
            reader = csv.DictReader(f)
            for row in reader:
                s_name = row['name']
                owner = row.get('owner_crew')
                f_id_sql = 'NULL'
                if owner:
                    for f_norm, f_sql in faction_name_map.items():
                        if f_norm in normalize_name(owner):
                            f_id_sql = f_sql
                            break
                            
                sql = f"""INSERT INTO op_ships (name, owner_faction_id, ship_type, description, status, special_abilities, image_url) VALUES (
                    {escape_sql(s_name)}, {f_id_sql}, {escape_sql(row.get('ship_type'))}, {escape_sql(row.get('description'))}, {escape_sql(row.get('status'))}, {escape_sql(row.get('special_abilities'))}, {escape_sql(row.get('image_url'))}
                ) ON CONFLICT (name) DO NOTHING;"""
                sql_lines.append(sql)

    # --- 10. SWORDS ---
    sql_lines.append("\n-- 10. Swords")
    swords_path = os.path.join(DATA_DIR, 'op_swords.csv')
    if not os.path.exists(swords_path):
        swords_path = os.path.join(DATA_DIR, 'swords.csv')
        
    if os.path.exists(swords_path):
        with open(swords_path, 'r', encoding='utf-8', errors='replace') as f:
            reader = csv.DictReader(f)
            for row in reader:
                sql = f"""INSERT INTO op_swords (name, grade, type, wielder_name, description, is_cursed, is_black_blade, image_url) VALUES (
                    {escape_sql(row['name'])}, {escape_sql(row.get('grade'))}, {escape_sql(row.get('type'))}, {escape_sql(row.get('wielder'))}, {escape_sql(row.get('description'))}, {escape_sql(row.get('is_cursed') == 'TRUE')}, {escape_sql(row.get('is_black_blade') == 'TRUE')}, {escape_sql(row.get('image_url'))}
                ) ON CONFLICT (name) DO NOTHING;"""
                sql_lines.append(sql)

    sql_lines.append("\nCOMMIT;")

    # Write huge file
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("\n".join(sql_lines))

if __name__ == "__main__":
    run_ultimate_reseed()
    print(f"ULTIMATE RESEED SQL generated in {OUTPUT_FILE}")
