-- Seed data for op_bounties
TRUNCATE TABLE op_bounties RESTART IDENTITY CASCADE;
INSERT INTO op_bounties (character_id, character_name, epithet, bounty_sequence, bounty_amount, bounty_status, reason_for_bounty, arc_revealed, chapter_revealed, crew_affiliation, notes) VALUES
(NULL, 'Monkey D. Luffy', 'Straw Hat', 1, 30000000, 'Inactive', 'Defeated Arlong and top East Blue pirates', 'East Blue Saga', 96, 'Straw Hat Pirates', 'First bounty in East Blue - highest in the region'),
(NULL, 'Monkey D. Luffy', 'Straw Hat', 2, 100000000, 'Inactive', 'Defeated Warlord Crocodile', 'Arabasta Saga', 213, 'Straw Hat Pirates', 'Credited to Smoker publicly'),
(NULL, 'Monkey D. Luffy', 'Straw Hat', 3, 300000000, 'Inactive', 'Assault on Enies Lobby and defeating CP9', 'Water 7 Saga', 435, 'Straw Hat Pirates', 'Became a Super Rookie'),
(NULL, 'Monkey D. Luffy', 'Straw Hat', 4, 400000000, 'Inactive', 'Summit War participation and Impel Down breakout', 'Post-War Arc', 601, 'Straw Hat Pirates', 'After Marineford War'),
(NULL, 'Monkey D. Luffy', 'Straw Hat', 5, 500000000, 'Inactive', 'Defeated Doflamingo', 'Dressrosa Arc', 801, 'Straw Hat Pirates', 'New wanted poster'),
(NULL, 'Monkey D. Luffy', 'Straw Hat', 6, 1500000000, 'Inactive', 'Whole Cake Island incident', 'Whole Cake Island Arc', 903, 'Straw Hat Pirates', 'Declared Fifth Emperor by media'),
(NULL, 'Monkey D. Luffy', 'Straw Hat', 7, 3000000000, 'Active', 'Defeated Kaido - Recognized as Yonko', 'Wano Country Arc', 1053, 'Straw Hat Pirates', 'Awakened Gear 5 form on poster'),
(NULL, 'Roronoa Zoro', 'Pirate Hunter', 1, 60000000, 'Inactive', 'Defeated Daz Bonez and 100 bounty hunters', 'Arabasta Saga', 213, 'Straw Hat Pirates', 'Broke East Blue bounty record'),
(NULL, 'Roronoa Zoro', 'Pirate Hunter', 2, 120000000, 'Inactive', 'Enies Lobby incident', 'Water 7 Saga', 435, 'Straw Hat Pirates', 'Became Super Rookie'),
(NULL, 'Roronoa Zoro', 'Pirate Hunter', 3, 320000000, 'Inactive', 'Dressrosa incident', 'Dressrosa Arc', 801, 'Straw Hat Pirates', 'New poster'),
(NULL, 'Roronoa Zoro', 'Pirate Hunter', 4, 1111000000, 'Active', 'Defeated King in Wano', 'Wano Country Arc', 1058, 'Straw Hat Pirates', 'Senior Officer of Grand Fleet'),
(NULL, 'Nami', 'Cat Burglar', 1, 16000000, 'Inactive', 'Enies Lobby incident', 'Water 7 Saga', 435, 'Straw Hat Pirates', 'Bikini photo by trick photographer'),
(NULL, 'Nami', 'Cat Burglar', 2, 66000000, 'Inactive', 'Dressrosa incident', 'Dressrosa Arc', 801, 'Straw Hat Pirates', 'Tricked into posing again'),
(NULL, 'Nami', 'Cat Burglar', 3, 366000000, 'Active', 'Wano Country raid', 'Wano Country Arc', 1058, 'Straw Hat Pirates', 'Senior Officer of Grand Fleet'),
(NULL, 'Usopp', 'Sogeking/God', 1, 30000000, 'Inactive', 'Shot World Government flag at Enies Lobby', 'Water 7 Saga', 435, 'Straw Hat Pirates', 'As Sogeking alter ego'),
(NULL, 'Usopp', 'God', 2, 200000000, 'Inactive', 'Dressrosa incident - became God Usopp', 'Dressrosa Arc', 801, 'Straw Hat Pirates', 'Changed to real identity and God title'),
(NULL, 'Usopp', 'God', 3, 500000000, 'Active', 'Wano Country raid', 'Wano Country Arc', 1058, 'Straw Hat Pirates', 'Senior Officer of Grand Fleet'),
(NULL, 'Sanji', 'Black Leg', 1, 77000000, 'Inactive', 'Enies Lobby incident', 'Water 7 Saga', 435, 'Straw Hat Pirates', 'Sketch drawing instead of photo'),
(NULL, 'Sanji', 'Black Leg', 2, 177000000, 'Inactive', 'Dressrosa incident', 'Dressrosa Arc', 801, 'Straw Hat Pirates', 'Only Alive condition by Judge''s interference'),
(NULL, 'Sanji', 'Black Leg', 3, 330000000, 'Inactive', 'Whole Cake Island incident', 'Whole Cake Island Arc', 903, 'Straw Hat Pirates', 'Name changed to Vinsmoke Sanji'),
(NULL, 'Sanji', 'Black Leg', 4, 1032000000, 'Active', 'Defeated Queen in Wano', 'Wano Country Arc', 1058, 'Straw Hat Pirates', 'Sketch drawing again on poster'),
(NULL, 'Tony Tony Chopper', 'Cotton Candy Lover', 1, 50, 'Inactive', 'Enies Lobby incident', 'Water 7 Saga', 435, 'Straw Hat Pirates', 'Mistaken for pet'),
(NULL, 'Tony Tony Chopper', 'Cotton Candy Lover', 2, 100, 'Inactive', 'Dressrosa incident', 'Dressrosa Arc', 801, 'Straw Hat Pirates', 'Still mistaken for pet'),
(NULL, 'Tony Tony Chopper', 'Cotton Candy Lover', 3, 1000, 'Active', 'Wano Country raid', 'Wano Country Arc', 1058, 'Straw Hat Pirates', 'Still low due to pet mistake'),
(NULL, 'Nico Robin', 'Devil Child', 1, 79000000, 'Inactive', 'Ohara incident at age 8', 'Enies Lobby Arc', 398, 'Baroque Works/Straw Hat Pirates', 'Can read Poneglyphs'),
(NULL, 'Nico Robin', 'Devil Child', 2, 80000000, 'Inactive', 'Enies Lobby incident', 'Water 7 Saga', 435, 'Straw Hat Pirates', 'Small increase'),
(NULL, 'Nico Robin', 'Devil Child', 3, 130000000, 'Inactive', 'Dressrosa incident', 'Dressrosa Arc', 801, 'Straw Hat Pirates', 'Updated poster'),
(NULL, 'Nico Robin', 'Devil Child', 4, 930000000, 'Active', 'Wano Country raid', 'Wano Country Arc', 1058, 'Straw Hat Pirates', 'Major jump due to Poneglyph knowledge'),
(NULL, 'Franky', 'Cyborg/Iron Man', 1, 44000000, 'Inactive', 'Enies Lobby incident', 'Water 7 Saga', 435, 'Straw Hat Pirates', 'Forced to join crew'),
(NULL, 'Franky', 'Cyborg/Iron Man', 2, 94000000, 'Inactive', 'Dressrosa incident', 'Dressrosa Arc', 801, 'Straw Hat Pirates', 'General Franky on poster'),
(NULL, 'Franky', 'Iron Man', 3, 394000000, 'Active', 'Wano Country raid', 'Wano Country Arc', 1058, 'Straw Hat Pirates', 'Thousand Sunny figurehead on poster'),
(NULL, 'Brook', 'Soul King', 1, 33000000, 'Inactive', 'As Rumbar Pirates member 50 years ago', 'Thriller Bark Arc', 489, 'Rumbar Pirates', 'Old bounty still active'),
(NULL, 'Brook', 'Soul King', 2, 83000000, 'Inactive', 'Dressrosa incident', 'Dressrosa Arc', 801, 'Straw Hat Pirates', 'Concert photo used'),
(NULL, 'Brook', 'Soul King', 3, 383000000, 'Active', 'Wano Country raid', 'Wano Country Arc', 1058, 'Straw Hat Pirates', 'Senior Officer of Grand Fleet'),
(NULL, 'Jinbe', 'Knight of the Sea', 1, 76000000, 'Inactive', 'Sun Pirates activities', 'Flashback', 620, 'Sun Pirates', 'Early Sun Pirates days'),
(NULL, 'Jinbe', 'Knight of the Sea', 2, 250000000, 'Inactive', 'Sun Pirates leader activities', 'Impel Down Arc', 528, 'Sun Pirates', 'Frozen as Warlord'),
(NULL, 'Jinbe', 'Knight of the Sea', 3, 438000000, 'Inactive', 'Marineford War participation', 'Post-War Arc', 601, 'Sun Pirates', 'Left Warlords'),
(NULL, 'Jinbe', 'Knight of the Sea', 4, 1100000000, 'Active', 'Wano Country raid', 'Wano Country Arc', 1058, 'Straw Hat Pirates', 'Senior Officer of Grand Fleet'),
(NULL, 'Gol D. Roger', 'Pirate King', 1, 5564800000, 'Inactive', 'Reached Laugh Tale and found One Piece', 'Zou Arc', 957, 'Roger Pirates', 'Highest bounty ever - expired after execution'),
(NULL, 'Edward Newgate', 'Whitebeard', 1, 5046000000, 'Inactive', 'Yonko status and Gura Gura no Mi', 'Zou Arc', 957, 'Whitebeard Pirates', 'Second highest bounty - died at Marineford'),
(NULL, 'Kaidou', 'of the Beasts', 1, 70000000, 'Inactive', 'Escaped Marine ship at age 13', 'Wano Country Arc', 1049, 'Beasts Pirates', 'First bounty as child'),
(NULL, 'Kaidou', 'of the Beasts', 2, 4611100000, 'Active', 'Yonko status', 'Zou Arc', 957, 'Beasts Pirates', 'Highest active bounty before defeat'),
(NULL, 'Charlotte Linlin', 'Big Mom', 1, 50000000, 'Inactive', 'At age 6 with Streusen', 'Whole Cake Island Arc', 868, 'Big Mom Pirates', 'Child bounty'),
(NULL, 'Charlotte Linlin', 'Big Mom', 2, 500000000, 'Inactive', 'Childhood piracy', 'Whole Cake Island Arc', 868, 'Big Mom Pirates', 'Still a child'),
(NULL, 'Charlotte Linlin', 'Big Mom', 3, 4388000000, 'Active', 'Yonko status and former Rocks Pirate', 'Zou Arc', 957, 'Big Mom Pirates', 'Fourth highest bounty'),
(NULL, 'Shanks', 'Red Hair', 1, 1040000000, 'Inactive', 'When visiting Foosha Village', 'Romance Dawn Arc', 1, 'Red Hair Pirates', '12 years before main story'),
(NULL, 'Shanks', 'Red Hair', 2, 4048900000, 'Active', 'Yonko status', 'Zou Arc', 957, 'Red Hair Pirates', 'Fifth highest bounty'),
(NULL, 'Marshall D. Teach', 'Blackbeard', 1, 2247600000, 'Inactive', 'Before attacking Hachinosu', 'Hachinosu Incident', 1059, 'Blackbeard Pirates', 'Initial Yonko bounty'),
(NULL, 'Marshall D. Teach', 'Blackbeard', 2, 3996000000, 'Active', 'Current Yonko status', 'Egghead Arc', 1059, 'Blackbeard Pirates', 'Only person with two Devil Fruits'),
(NULL, 'Dracule Mihawk', 'Hawk Eyes', 1, 3590000000, 'Active', 'After Warlord abolishment', 'Egghead Arc', 1058, 'Cross Guild', 'World''s Strongest Swordsman'),
(NULL, 'Buggy', 'The Clown/The Star Clown', 1, 15000000, 'Inactive', 'Pre-Grand Line activities', 'Orange Town Arc', 9, 'Buggy Pirates', 'Former Roger Pirates member'),
(NULL, 'Buggy', 'The Clown/The Star Clown', 2, 3189000000, 'Active', 'Cross Guild leader and Yonko', 'Egghead Arc', 1058, 'Cross Guild', 'Highest bounty increase ever'),
(NULL, 'Crocodile', 'Sir/Desert King', 1, 81000000, 'Inactive', 'Pre-Warlord activities', 'Arabasta Arc', 155, 'Baroque Works', 'Frozen as Warlord'),
(NULL, 'Crocodile', 'Sir', 2, 1965000000, 'Active', 'Cross Guild co-founder', 'Egghead Arc', 1058, 'Cross Guild', 'Massive increase after abolishment'),
(NULL, 'Trafalgar Law', 'Surgeon of Death', 1, 200000000, 'Inactive', 'Supernova activities', 'Sabaody Arc', 498, 'Heart Pirates', 'Super Rookie'),
(NULL, 'Trafalgar Law', 'Surgeon of Death', 2, 440000000, 'Inactive', 'Pre-Warlord', 'Punk Hazard Arc', 659, 'Heart Pirates', 'Frozen as Warlord'),
(NULL, 'Trafalgar Law', 'Surgeon of Death', 3, 500000000, 'Inactive', 'Defeated Doflamingo', 'Dressrosa Arc', 801, 'Heart Pirates', 'Warlord dismissed'),
(NULL, 'Trafalgar Law', 'Surgeon of Death', 4, 3000000000, 'Active', 'Defeated Big Mom with Kid', 'Wano Country Arc', 1053, 'Heart Pirates', 'Same as Luffy and Kid'),
(NULL, 'Eustass Kid', 'Captain', 1, 315000000, 'Inactive', 'Attacking civilians in Grand Line', 'Sabaody Arc', 498, 'Kid Pirates', 'Highest Supernova bounty'),
(NULL, 'Eustass Kid', 'Captain', 2, 470000000, 'Inactive', 'Post-timeskip activities', 'Dressrosa Arc', 677, 'Kid Pirates', 'Two-year increase'),
(NULL, 'Eustass Kid', 'Captain', 3, 3000000000, 'Active', 'Defeated Big Mom with Law', 'Wano Country Arc', 1053, 'Kid Pirates', 'Same as Luffy and Law'),
(NULL, 'Loki', 'Accursed Prince', 1, 2600000000, 'Active', 'Special circumstances in Elbaf', 'Elbaf Arc', 1131, 'Elbaf', 'Imprisoned prince with special bounty'),
(NULL, 'Dorry', 'Blue Ogre', 1, 100000000, 'Inactive', '100+ year old bounty', 'Little Garden Arc', 118, 'Giant Warrior Pirates', 'Never updated for century'),
(NULL, 'Dorry', 'Blue Ogre', 2, 1800000000, 'Active', 'Egghead incident with inflation adjustment', 'Egghead Arc', 1130, 'Giant Warrior Pirates', 'Inflation adjusted'),
(NULL, 'Brogy', 'Red Ogre', 1, 100000000, 'Inactive', '100+ year old bounty', 'Little Garden Arc', 118, 'Giant Warrior Pirates', 'Never updated for century'),
(NULL, 'Brogy', 'Red Ogre', 2, 1800000000, 'Active', 'Egghead incident with inflation adjustment', 'Egghead Arc', 1130, 'Giant Warrior Pirates', 'Inflation adjusted'),
(NULL, 'Boa Hancock', 'Pirate Empress', 1, 80000000, 'Inactive', 'Single campaign as Kuja captain', 'Amazon Lily Arc', 516, 'Kuja Pirates', 'Age 18 - frozen as Warlord'),
(NULL, 'Boa Hancock', 'Pirate Empress', 2, 1659000000, 'Active', 'Warlord abolishment', 'Egghead Arc', 1059, 'Kuja Pirates', 'Massive increase'),
(NULL, 'King', 'The Conflagration', 1, 1390000000, 'Active', 'All-Star of Beasts Pirates', 'Wano Country Arc', 1035, 'Beasts Pirates', 'Last Lunarian'),
(NULL, 'Marco', 'The Phoenix', 1, 1374000000, 'Active', 'First Division Commander', 'Wano Country Arc', 1028, 'Whitebeard Pirates', 'Mythical Zoan user'),
(NULL, 'Queen', 'The Plague', 1, 1320000000, 'Active', 'All-Star of Beasts Pirates', 'Wano Country Arc', 935, 'Beasts Pirates', 'Former MADS member'),
(NULL, 'Charlotte Katakuri', NULL, 1, 1057000000, 'Active', 'Sweet Commander', 'Whole Cake Island Arc', 860, 'Big Mom Pirates', 'Second son'),
(NULL, 'Jack', 'The Drought', 1, 1000000000, 'Active', 'All-Star of Beasts Pirates', 'Zou Arc', 808, 'Beasts Pirates', 'First billion berry bounty revealed'),
(NULL, 'Charlotte Smoothie', NULL, 1, 932000000, 'Active', 'Sweet Commander', 'Whole Cake Island Arc', 846, 'Big Mom Pirates', '14th daughter'),
(NULL, 'Charlotte Cracker', 'Thousand Arms', 1, 860000000, 'Active', 'Sweet Commander', 'Whole Cake Island Arc', 846, 'Big Mom Pirates', 'Biscuit Soldier on poster'),
(NULL, 'Charlotte Perospero', NULL, 1, 700000000, 'Active', 'Eldest Charlotte child', 'Whole Cake Island Arc', 846, 'Big Mom Pirates', 'Officer'),
(NULL, 'Charlotte Snack', NULL, 1, 600000000, 'Active', 'Former Sweet Commander', 'Whole Cake Island Arc', 894, 'Big Mom Pirates', 'Lost position to Cracker'),
(NULL, 'Portgas D. Ace', 'Fire Fist', 1, 550000000, 'Inactive', 'Whitebeard 2nd Division Commander', 'Marineford Arc', 157, 'Whitebeard Pirates', 'Died at Marineford'),
(NULL, 'Little Oars Jr.', NULL, 1, 550000000, 'Active', 'Whitebeard subordinate', 'Marineford Arc', 554, 'Little Pirates', 'Giant descendant of Oars'),
(NULL, 'Who''s-Who', 'Who of the Droplets', 1, 546000000, 'Active', 'Tobiroppo member', 'Wano Country Arc', 998, 'Beasts Pirates', 'Former CP9 agent'),
(NULL, 'Chinjao', 'The Drill', 1, 542000000, 'Active', 'Former pirate and Happo Navy leader', 'Dressrosa Arc', 719, 'Happo Navy', '30 year old bounty'),
(NULL, 'Izou', NULL, 1, 510000000, 'Inactive', '16th Division Commander', 'Wano Country Arc', 1053, 'Whitebeard Pirates', 'Died in Wano'),
(NULL, 'Ulti', NULL, 1, 400000000, 'Active', 'Tobiroppo member', 'Wano Country Arc', 998, 'Beasts Pirates', 'Page One''s sister'),
(NULL, 'Black Maria', NULL, 1, 480000000, 'Active', 'Tobiroppo member', 'Wano Country Arc', 998, 'Beasts Pirates', 'Pleasure District manager'),
(NULL, 'Sasaki', NULL, 1, 472000000, 'Active', 'Tobiroppo member', 'Wano Country Arc', 998, 'Beasts Pirates', 'Ancient Zoan user'),
(NULL, 'Belo Betty', NULL, 1, 457000000, 'Active', 'Revolutionary Army Commander', 'Levely Arc', 904, 'Revolutionary Army', 'Highest female non-pirate bounty'),
(NULL, 'Tamago', 'Baron', 1, 429000000, 'Active', 'Big Mom combatant', 'Whole Cake Island Arc', 850, 'Big Mom Pirates', 'Evolves when defeated'),
(NULL, 'Karasu', NULL, 1, 400000000, 'Active', 'Revolutionary Army Commander', 'Levely Arc', 904, 'Revolutionary Army', 'North Army commander'),
(NULL, 'Pedro', 'of the Treetops', 1, 382000000, 'Inactive', 'Former Nox Pirates captain', 'Whole Cake Island Arc', 850, 'Nox Pirates', 'Died at Whole Cake Island'),
(NULL, 'Scratchmen Apoo', 'Roar of the Sea', 1, 198000000, 'Inactive', 'Supernova activities', 'Sabaody Arc', 498, 'On Air Pirates', 'Super Rookie'),
(NULL, 'Scratchmen Apoo', 'Roar of the Sea', 2, 350000000, 'Active', 'Post-timeskip', 'Dressrosa Arc', 677, 'Beasts Pirates', 'Allied with Kaido'),
(NULL, 'Capone Bege', 'Gang', 1, 138000000, 'Inactive', 'Targeted renowned captains', 'Sabaody Arc', 498, 'Fire Tank Pirates', 'Super Rookie'),
(NULL, 'Capone Bege', 'Gang', 2, 300000000, 'Inactive', 'Post-timeskip', 'Dressrosa Arc', 677, 'Fire Tank Pirates', 'Allied with Big Mom'),
(NULL, 'Capone Bege', 'Gang', 3, 350000000, 'Active', 'Big Mom assassination plot', 'Whole Cake Island Arc', 903, 'Fire Tank Pirates', 'Left Big Mom alliance'),
(NULL, 'Cavendish', 'White Horse', 1, 280000000, 'Inactive', 'Beautiful Pirates captain', 'Dressrosa Arc', 704, 'Beautiful Pirates', 'Hakuba personality'),
(NULL, 'Cavendish', 'White Horse', 2, 330000000, 'Active', 'Defeated Doflamingo crew', 'Dressrosa Arc', 801, 'Straw Hat Grand Fleet', 'Grand Fleet Division 1 leader'),
(NULL, 'Pekoms', NULL, 1, 330000000, 'Active', 'Big Mom combatant', 'Fish-Man Island Arc', 651, 'Big Mom Pirates', 'Mink tribe'),
(NULL, 'Jewelry Bonney', 'Big Eater', 1, 140000000, 'Inactive', 'Supernova activities', 'Sabaody Arc', 498, 'Bonney Pirates', 'Super Rookie'),
(NULL, 'Jewelry Bonney', 'Big Eater', 2, 320000000, 'Active', 'Post-timeskip', 'Egghead Arc', 1060, 'Bonney Pirates', 'Age-manipulation powers'),
(NULL, 'Basil Hawkins', 'The Magician', 1, 249000000, 'Inactive', 'Supernova activities', 'Sabaody Arc', 498, 'Hawkins Pirates', 'Super Rookie'),
(NULL, 'Basil Hawkins', 'The Magician', 2, 320000000, 'Active', 'Post-timeskip', 'Dressrosa Arc', 677, 'Beasts Pirates', 'Allied with Kaido'),
(NULL, 'Donquixote Doflamingo', 'Heavenly Yaksha', 1, 340000000, 'Inactive', 'Pre-Warlord activities', 'Jaya Arc', 234, 'Donquixote Pirates', 'Frozen as Warlord 10 years'),
(NULL, 'Lindbergh', NULL, 1, 316000000, 'Active', 'Revolutionary Army Commander', 'Levely Arc', 904, 'Revolutionary Army', 'South Army commander'),
(NULL, 'Caesar Clown', 'Master', 1, 300000000, 'Active', 'Illegal experiments and prison escape', 'Punk Hazard Arc', 671, 'Donquixote Pirates', 'Former Marine scientist'),
(NULL, 'Charlotte Daifuku', NULL, 1, 300000000, 'Active', 'Charlotte officer', 'Whole Cake Island Arc', 846, 'Big Mom Pirates', '3rd son'),
(NULL, 'Charlotte Oven', NULL, 1, 300000000, 'Active', 'Charlotte officer', 'Whole Cake Island Arc', 846, 'Big Mom Pirates', '4th son'),
(NULL, 'Bartholomew Kuma', 'The Tyrant', 1, 296000000, 'Inactive', 'Sank Marine fleet', 'Thriller Bark Arc', 234, 'Revolutionary Army', 'Frozen as Warlord'),
(NULL, 'Morley', NULL, 1, 293000000, 'Active', 'Revolutionary Army Commander', 'Levely Arc', 904, 'Revolutionary Army', 'West Army commander and former pirate'),
(NULL, 'Page One', NULL, 1, 290000000, 'Active', 'Tobiroppo member', 'Wano Country Arc', 998, 'Beasts Pirates', 'Ulti''s brother'),
(NULL, 'X Drake', 'Red Flag', 1, 222000000, 'Active', 'Alleged Marine betrayal', 'Sabaody Arc', 498, 'Drake Pirates', 'Secret SWORD member'),
(NULL, 'Sai', 'Don Sai', 1, 210000000, 'Active', 'Happo Navy leader', 'Dressrosa Arc', 758, 'Straw Hat Grand Fleet', 'Grand Fleet Division 3 leader'),
(NULL, 'Squard', 'Maelstrom Spider', 1, 210000000, 'Active', 'Whitebeard subordinate', 'Marineford Arc', 551, 'Spade Pirates', 'Betrayed by Akainu''s lies'),
(NULL, 'Caribou', 'Wet-Haired', 1, 210000000, 'Active', 'Killing Marines', 'Sabaody Arc', 600, 'Caribou Pirates', 'Logia user'),
(NULL, 'Killer', 'Massacre Soldier', 1, 162000000, 'Inactive', 'Supernova activities', 'Sabaody Arc', 498, 'Kid Pirates', 'Super Rookie'),
(NULL, 'Killer', 'Massacre Soldier', 2, 200000000, 'Active', 'Post-timeskip', 'Dressrosa Arc', 677, 'Kid Pirates', 'Always wears mask'),
(NULL, 'Bellamy', 'The Hyena', 1, 55000000, 'Inactive', 'Big-Time Rookie', 'Jaya Arc', 222, 'Bellamy Pirates', 'Mocked dreams'),
(NULL, 'Bellamy', 'The Hyena', 2, 195000000, 'Active', 'Post-timeskip activities', 'Dressrosa Arc', 706, 'Donquixote Pirates', 'Allied with Doflamingo'),
(NULL, 'Ginny', NULL, 1, 190000000, 'Inactive', 'Revolutionary Army activities', 'Egghead Arc', 1098, 'Revolutionary Army', 'Died - bounty no longer claimable'),
(NULL, 'Coribou', 'Blood-Splatterer', 1, 190000000, 'Active', 'Killing Marines', 'Sabaody Arc', 600, 'Caribou Pirates', 'Caribou''s brother'),
(NULL, 'Orlumbus', 'Massacre Ruler', 1, 148000000, 'Active', 'Yonta Maria Grand Fleet admiral', 'Dressrosa Arc', 800, 'Straw Hat Grand Fleet', 'Grand Fleet Division 7 leader'),
(NULL, 'Urouge', 'Mad Monk', 1, 108000000, 'Active', 'Supernova activities', 'Sabaody Arc', 498, 'Fallen Monk Pirates', 'Super Rookie from sky island'),
(NULL, 'Bobbin', 'Sweeper', 1, 105500000, 'Active', 'Big Mom combatant', 'Whole Cake Island Arc', 834, 'Big Mom Pirates', 'Bishop rank'),
(NULL, 'Trebol', NULL, 1, 99000000, 'Inactive', 'Donquixote officer', 'Dressrosa Arc', 682, 'Donquixote Pirates', 'Frozen 10 years as Warlord subordinate'),
(NULL, 'Diamante', NULL, 1, 99000000, 'Inactive', 'Donquixote officer', 'Dressrosa Arc', 682, 'Donquixote Pirates', 'Frozen 10 years as Warlord subordinate'),
(NULL, 'Pica', NULL, 1, 99000000, 'Inactive', 'Donquixote officer', 'Dressrosa Arc', 682, 'Donquixote Pirates', 'Frozen 10 years as Warlord subordinate'),
(NULL, 'Vito', 'Monster Gun', 1, 95000000, 'Active', 'Fire Tank combatant', 'Whole Cake Island Arc', 825, 'Fire Tank Pirates', 'Bege''s subordinate'),
(NULL, 'Rockstar', NULL, 1, 94000000, 'Active', 'Red Hair Pirates member', 'Jaya Arc', 234, 'Red Hair Pirates', 'Messenger for Shanks'),
(NULL, 'Vander Decken IX', NULL, 1, 94000000, 'Active', 'Flying Pirates captain', 'Fish-Man Island Arc', 606, 'Flying Pirates', 'Cursed to touch nothing'),
(NULL, 'Gotti', NULL, 1, 90000000, 'Active', 'Fire Tank combatant', 'Whole Cake Island Arc', 825, 'Fire Tank Pirates', 'Bege''s subordinate'),
(NULL, 'Lip Doughty', 'Service', 1, 88000000, 'Inactive', 'Fake Straw Hat member', 'Return to Sabaody Arc', 600, 'Fake Straw Hat Crew', 'Arrested by Sentomaru'),
(NULL, 'Albion', 'Gashed', 1, 92000000, 'Active', 'New World pirate', 'Return to Sabaody Arc', 600, 'Unknown', 'Tried to join fake Straw Hats'),
(NULL, 'Brownbeard', NULL, 1, 80060000, 'Inactive', 'New World pirate', 'Punk Hazard Arc', 661, 'Centaur Patrol', 'Captured by Caesar then arrested'),
(NULL, 'Daz Bonez', 'The Killer', 1, 75000000, 'Active', 'Baroque Works officer', 'Arabasta Arc', 190, 'Cross Guild', 'Mr. 1'),
(NULL, 'Gyro', 'Crab-Hand', 1, 73000000, 'Active', 'South Blue pirate', 'Fish-Man Island Arc', 612, 'Gyro Pirates', 'Turned into centaur by Caesar'),
(NULL, 'Hody Jones', NULL, 1, 73000000, 'Active', 'New Fishman Pirates captain', 'Fish-Man Island Arc', 644, 'New Fishman Pirates', 'Energy Steroid user'),
(NULL, 'Suleiman', 'The Beheader', 1, 67000000, 'Active', 'War criminal', 'Dressrosa Arc', 706, 'Beautiful Pirates', 'Joined Cavendish'),
(NULL, 'Gambia', 'Missionary', 1, 67000000, 'Active', 'Barto Club officer', 'Dressrosa Arc', 706, 'Barto Club', 'Fanatical Luffy fan'),
(NULL, 'Devil Dias', NULL, 1, 60000000, 'Inactive', 'Paradise pirate', 'Sabaody Arc', 497, 'Unknown', 'Carried off by Marines'),
(NULL, 'Senor Pink', NULL, 1, 58000000, 'Inactive', 'Donquixote officer', 'Dressrosa Arc', 775, 'Donquixote Pirates', 'Frozen 10 years as Warlord subordinate'),
(NULL, 'Kelly Funk', NULL, 1, 57000000, 'Active', 'Assassin', 'Dressrosa Arc', 706, 'Mogaro Kingdom', 'Works with brother Bobby'),
(NULL, 'Peachbeard', NULL, 1, 52000000, 'Active', 'Blackbeard subordinate', 'Dressrosa Arc', 925, 'Blackbeard Pirates', 'Allied with Blackbeard'),
(NULL, 'Boa Sandersonia', NULL, 1, 40000000, 'Active', 'Kuja Pirates member', 'Amazon Lily Arc', 516, 'Kuja Pirates', 'Hancock''s sister'),
(NULL, 'Boa Marigold', NULL, 1, 40000000, 'Active', 'Kuja Pirates member', 'Amazon Lily Arc', 516, 'Kuja Pirates', 'Hancock''s sister'),
(NULL, 'Roshio', 'The Executioner', 1, 42000000, 'Active', 'Paradise pirate', 'Jaya Arc', 222, 'Unknown', 'Mock Town resident'),
(NULL, 'Mikazuki', NULL, 1, 36000000, 'Active', 'Paradise pirate', 'Jaya Arc', 222, 'Unknown', 'Mock Town resident'),
(NULL, 'Shoujou', 'Sonar King', 1, 36000000, 'Active', 'Saruyama Alliance', 'Jaya Arc', 227, 'Shoujou Pirates', 'Salvage operations'),
(NULL, 'Bobby Funk', NULL, 1, 36000000, 'Active', 'Assassin', 'Dressrosa Arc', 706, 'Mogaro Kingdom', 'Works with brother Kelly'),
(NULL, 'Zala', 'Poison Spider', 1, 35000000, 'Active', 'Baroque Works officer', 'Arabasta Arc', 190, 'Unknown', 'Miss Doublefinger'),
(NULL, 'Bentham', 'of the Wild', 1, 32000000, 'Inactive', 'Baroque Works officer', 'Arabasta Arc', 161, 'Unknown', 'Mr. 2 Bon Kurei - captured twice'),
(NULL, 'Gladius', NULL, 1, 31000000, 'Inactive', 'Donquixote officer', 'Dressrosa Arc', 706, 'Donquixote Pirates', 'Frozen 10 years as Warlord subordinate'),
(NULL, 'Marianne', 'Flag-Bearer of Freedom', 1, 29000000, 'Active', 'Baroque Works officer', 'Arabasta Arc', 161, 'Unknown', 'Miss Goldenweek'),
(NULL, 'Demalo Black', 'Three Tongued', 1, 26000000, 'Inactive', 'Fake Luffy', 'Return to Sabaody Arc', 598, 'Fake Straw Hat Crew', 'Arrested by Sentomaru'),
(NULL, 'Mont Blanc Cricket', NULL, 1, 25000000, 'Active', 'Saruyama Alliance leader', 'Jaya Arc', 227, 'Saruyama Alliance', 'Descendant of Noland'),
(NULL, 'Charlotte Lola', NULL, 1, 24000000, 'Active', 'Former Big Mom Pirates', 'Thriller Bark Arc', 449, 'Rolling Pirates', 'Big Mom''s daughter who fled'),
(NULL, 'Foxy', 'Silver Fox', 1, 24000000, 'Active', 'Foxy Pirates captain', 'Long Ring Long Land Arc', 305, 'Foxy Pirates', 'Davy Back Fight specialist'),
(NULL, 'Galdino', 'Loan Shark', 1, 24000000, 'Active', 'Former Baroque Works', 'Arabasta Arc', 161, 'Cross Guild', 'Mr. 3'),
(NULL, 'Masira', 'Salvage King', 1, 23000000, 'Active', 'Saruyama Alliance', 'Jaya Arc', 227, 'Masira Pirates', 'Salvage operations'),
(NULL, 'Arlong', 'Saw-Tooth', 1, 20000000, 'Inactive', 'Arlong Pirates captain', 'Arlong Park Arc', 69, 'Arlong Pirates', 'Highest East Blue bounty - captured'),
(NULL, 'Lacuba', NULL, 1, 17000000, 'Active', 'Paradise pirate', 'Sabaody Arc', 497, 'Unknown', 'Escaped Human Auction House'),
(NULL, 'Don Krieg', 'Pirate Admiral', 1, 17000000, 'Inactive', 'Krieg Pirates admiral', 'Baratie Arc', 47, 'Krieg Pirates', 'Strongest East Blue fleet'),
(NULL, 'Kuro', 'Of a Hundred Plans', 1, 16000000, 'Inactive', 'Black Cat Pirates captain', 'Syrup Village Arc', 33, 'Black Cat Pirates', 'Faked death'),
(NULL, 'Dellinger', NULL, 1, 15000000, 'Inactive', 'Donquixote officer', 'Dressrosa Arc', 706, 'Donquixote Pirates', 'Half fighting fish'),
(NULL, 'Drophy', 'Town-Collapser', 1, 14000000, 'Active', 'Baroque Works officer', 'Arabasta Arc', 161, 'Unknown', 'Miss Merry Christmas'),
(NULL, 'Curly Dadan', NULL, 1, 7800000, 'Active', 'Mountain bandit', 'Post-War Arc', 582, 'Dadan Family', 'Raised Luffy and Ace'),
(NULL, 'Gin', 'Man-Demon', 1, 12000000, 'Inactive', 'Krieg combat commander', 'Baratie Arc', 47, 'Krieg Pirates', 'Ruthless nature'),
(NULL, 'Machvise', NULL, 1, 11000000, 'Inactive', 'Donquixote officer', 'Dressrosa Arc', 706, 'Donquixote Pirates', 'Ton Ton fruit user'),
(NULL, 'Gem', 'of the Border', 1, 10000000, 'Active', 'Baroque Works officer', 'Whisky Peak Arc', 110, 'Unknown', 'Mr. 5'),
(NULL, 'Wellington', NULL, 1, 10000000, 'Active', 'North Blue pirate', 'Jaya Arc', 222, 'Unknown', 'Mock Town resident'),
(NULL, 'Jango', 'The Hypnotist', 1, 9000000, 'Inactive', 'Former Black Cat officer', 'Syrup Village Arc', 38, 'Marines', 'Joined Marines'),
(NULL, 'Kuroobi', NULL, 1, 9000000, 'Inactive', 'Arlong officer', 'Arlong Park Arc', SBS, 'Arlong Pirates', 'Ray martial artist - captured'),
(NULL, 'Higuma', NULL, 1, 8000000, 'Inactive', 'Mountain bandit', 'Romance Dawn Arc', 1, 'Higuma Bandits', NULL),
(NULL, 'Gol D. Roger', 'King of the Pirates', 1, 5564800000, 'Inactive (Deceased)', 'Conquered the Grand Line / Learned True History', 'Wano Country', 957, 'Roger Pirates', 'Highest known pirate bounty in history.'),
(NULL, 'Edward Newgate', 'Whitebeard', 1, 5046000000, 'Inactive (Deceased)', 'Power to destroy the world / Yonko status', 'Wano Country', 957, 'Whitebeard Pirates', 'Former Rival to Roger.'),
(NULL, 'Kaido', 'King of the Beasts', 1, 4611100000, 'Active (Status Unknown)', 'Yonko status / Tyranny in Wano', 'Wano Country', 957, 'Beasts Pirates', 'Defeated by Luffy.'),
(NULL, 'Charlotte Linlin', 'Big Mom', 1, 4388000000, 'Active (Status Unknown)', 'Yonko status / Ruler of Totto Land', 'Wano Country', 957, 'Big Mom Pirates', 'Defeated by Kid and Law.'),
(NULL, 'Shanks', 'Red-Haired', 1, 4048900000, 'Active', 'Yonko status / Diplomatic influence', 'Wano Country', 957, 'Red Hair Pirates', 'Youngest of the original Yonko.'),
(NULL, 'Marshall D. Teach', 'Blackbeard', 1, 0, 'Revoked (Updated)', 'Warlord appointment', 'Post-Enies Lobby', 474, 'Blackbeard Pirates', 'Former Whitebeard member.'),
(NULL, 'Marshall D. Teach', 'Blackbeard', 2, 2247600000, 'Active (Outdated)', 'Yonko status / Two Devil Fruits', 'Post-Dressrosa', 925, 'Blackbeard Pirates', 'First bounty as Yonko.'),
(NULL, 'Marshall D. Teach', 'Blackbeard', 3, 3996000000, 'Active', 'Defeating Heart Pirates / Expanding territory', 'Egghead', 1063, 'Blackbeard Pirates', 'Current bounty.'),
(NULL, 'Dracule Mihawk', 'Hawk Eyes', 1, 3590000000, 'Active', 'World''s Strongest Swordsman / Cross Guild Founder', 'Egghead', 1058, 'Cross Guild', 'Higher bounty than his nominal leader Buggy.'),
(NULL, 'Buggy', 'The Genius Jester', 1, 15000000, 'Revoked (Updated)', 'Terrorizing East Blue', 'Orange Town', 19, 'Buggy Pirates', 'Early East Blue villain.'),
(NULL, 'Buggy', 'The Genius Jester', 2, 3189000000, 'Active', 'Figurehead Leader of Cross Guild / Yonko Status', 'Egghead', 1058, 'Cross Guild', 'Fails upwards successfully.'),
(NULL, 'Monkey D. Luffy', 'Straw Hat', 1, 30000000, 'Active (Updated)', 'Defeating Arlong / East Blue dominance', 'Loguetown', 96, 'Straw Hat Pirates', 'First bounty.'),
(NULL, 'Monkey D. Luffy', 'Straw Hat', 2, 100000000, 'Active (Updated)', 'Defeating Crocodile (Warlord)', 'Jaya', 232, 'Straw Hat Pirates', 'Declared Supernova.'),
(NULL, 'Monkey D. Luffy', 'Straw Hat', 3, 300000000, 'Active (Updated)', 'Enies Lobby raid / Defeating Rob Lucci', 'Post-Enies Lobby', 435, 'Straw Hat Pirates', 'Declared war on World Govt.'),
(NULL, 'Monkey D. Luffy', 'Straw Hat', 4, 400000000, 'Active (Updated)', 'Impel Down breakout / Marineford War', 'Return to Sabaody', 601, 'Straw Hat Pirates', 'Post-Timeskip reveal.'),
(NULL, 'Monkey D. Luffy', 'Straw Hat', 5, 500000000, 'Active (Updated)', 'Defeating Doflamingo / Dressrosa alliance', 'Post-Dressrosa', 801, 'Straw Hat Pirates', 'Grand Fleet formed.'),
(NULL, 'Monkey D. Luffy', 'Straw Hat', 6, 1500000000, 'Active (Updated)', 'Invading Totto Land / Defeating Katakuri', 'Post-WCI', 903, 'Straw Hat Pirates', 'Declared Fifth Emperor (unofficially).'),
(NULL, 'Monkey D. Luffy', 'Straw Hat', 7, 3000000000, 'Active', 'Defeating Kaido / Joyboy Awakening', 'Post-Wano', 1053, 'Straw Hat Pirates', 'Officially a Yonko.'),
(NULL, 'Monkey D. Garp', 'The Fist', 1, 3000000000, 'Active', 'Cross Guild Marine Bounty (3 Crowns)', 'Egghead', 1056, 'Marines', 'Equal to an Admiral in Cross Guild eyes.'),
(NULL, 'Trafalgar Law', 'Surgeon of Death', 1, 200000000, 'Active (Updated)', 'Rookie actions', 'Sabaody', 498, 'Heart Pirates', 'Supernova Era.'),
(NULL, 'Trafalgar Law', 'Surgeon of Death', 2, 440000000, 'Frozen (Warlord)', 'Rocky Port Incident', 'Punk Hazard', 659, 'Heart Pirates', 'Became Warlord.'),
(NULL, 'Trafalgar Law', 'Surgeon of Death', 3, 500000000, 'Active (Updated)', 'Alliance with Straw Hats / Dressrosa', 'Post-Dressrosa', 801, 'Heart Pirates', 'Warlord title revoked.'),
(NULL, 'Trafalgar Law', 'Surgeon of Death', 4, 3000000000, 'Active', 'Defeating Big Mom', 'Post-Wano', 1053, 'Heart Pirates', 'Shares value with Luffy/Kid.'),
(NULL, 'Eustass Kid', 'Captain', 1, 315000000, 'Active (Updated)', 'Civilian casualties / Rookie actions', 'Sabaody', 498, 'Kid Pirates', 'Highest Supernova bounty pre-skip.'),
(NULL, 'Eustass Kid', 'Captain', 2, 470000000, 'Active (Updated)', 'New World aggression', 'Post-Timeskip', 601, 'Kid Pirates', 'Targeted Shanks'' fleet.'),
(NULL, 'Eustass Kid', 'Captain', 3, 3000000000, 'Active', 'Defeating Big Mom', 'Post-Wano', 1053, 'Kid Pirates', 'Currently defeated by Shanks.'),
(NULL, 'Sir Crocodile', 'Desert King', 1, 81000000, 'Frozen (Updated)', 'Logia user / Pirate acts', 'Alabasta', 155, 'Baroque Works', 'Frozen when became Warlord.'),
(NULL, 'Sir Crocodile', 'Desert King', 2, 1965000000, 'Active', 'Logia Mastery / Cross Guild Leadership / Cunning', 'Egghead', 1058, 'Cross Guild', 'Massive jump due to threat level.'),
(NULL, 'Boa Hancock', 'Pirate Empress', 1, 80000000, 'Frozen (Updated)', 'Single campaign', 'Amazon Lily', 522, 'Kuja Pirates', 'Frozen instantly for Warlord status.'),
(NULL, 'Boa Hancock', 'Pirate Empress', 2, 1659000000, 'Active', 'Warlord revocation / Haki / Threat to Govt', 'Egghead', 1059, 'Kuja Pirates', 'High threat assessment.'),
(NULL, 'King', 'The Wildfire', 1, 1390000000, 'Active', 'Kaido''s Right Hand / Lunarian Race', 'Wano Country', 957, 'Beasts Pirates', 'Defeated by Zoro.'),
(NULL, 'Marco', 'The Phoenix', 1, 1374000000, 'Active', 'Whitebeard''s Right Hand / Marineford War', 'Wano Country', 957, 'Whitebeard Pirates', 'Leader of the Remnants.'),
(NULL, 'Queen', 'The Plague', 1, 1320000000, 'Active', 'MADS Scientist / Kaido''s Commander', 'Wano Country', 935, 'Beasts Pirates', 'Defeated by Sanji.'),
(NULL, 'Roronoa Zoro', 'Pirate Hunter', 1, 60000000, 'Active (Updated)', 'Defeating Daz Bonez / 100 Bounty Hunters', 'Alabasta', 213, 'Straw Hat Pirates', 'First bounty.'),
(NULL, 'Roronoa Zoro', 'Pirate Hunter', 2, 120000000, 'Active (Updated)', 'Enies Lobby / Defeating Kaku', 'Post-Enies Lobby', 435, 'Straw Hat Pirates', 'Supernova status.'),
(NULL, 'Roronoa Zoro', 'Pirate Hunter', 3, 320000000, 'Active (Updated)', 'Dressrosa / Defeating Pica', 'Post-Dressrosa', 801, 'Straw Hat Pirates', 'Crossed 300M mark.'),
(NULL, 'Roronoa Zoro', 'Pirate Hunter', 4, 1111000000, 'Active', 'Defeating King / Conqueror''s Haki', 'Post-Wano', 1058, 'Straw Hat Pirates', 'The "Number 2" of the crew.'),
(NULL, 'Jinbe', 'Knight of the Sea', 1, 76000000, 'Active (Updated)', 'Sun Pirates activity', 'Fishman Island', 628, 'Sun Pirates', 'Pre-Warlord.'),
(NULL, 'Jinbe', 'Knight of the Sea', 2, 250000000, 'Frozen (Updated)', 'Warlord appointment', 'Impel Down', 528, 'Sun Pirates', 'Frozen era.'),
(NULL, 'Jinbe', 'Knight of the Sea', 3, 438000000, 'Active (Updated)', 'Resignation from Warlords / Marineford', 'Post-Timeskip', 635, 'Straw Hat Pirates', 'Joined Straw Hats.'),
(NULL, 'Jinbe', 'Knight of the Sea', 4, 1100000000, 'Active', 'Defeating Who''s Who / Senior Officer status', 'Post-Wano', 1058, 'Straw Hat Pirates', 'Third highest in crew.'),
(NULL, 'Charlotte Katakuri', 'Dogtooth', 1, 1057000000, 'Active', 'Big Mom''s Strongest Commander', 'WCI', 860, 'Big Mom Pirates', 'Undefeated until Luffy.'),
(NULL, 'Vinsmoke Sanji', 'Black Leg', 1, 77000000, 'Active (Updated)', 'Enies Lobby / Defeating Jabra', 'Post-Enies Lobby', 435, 'Straw Hat Pirates', 'Photo was a doodle.'),
(NULL, 'Vinsmoke Sanji', 'Black Leg', 2, 177000000, 'Active (Updated)', 'Dressrosa (Only Alive status)', 'Post-Dressrosa', 801, 'Straw Hat Pirates', 'Vinsmoke name leverage.'),
(NULL, 'Vinsmoke Sanji', 'Black Leg', 3, 330000000, 'Active (Updated)', 'WCI / Vinsmoke assassination plot', 'Post-WCI', 903, 'Straw Hat Pirates', 'Restored to Dead or Alive.'),
(NULL, 'Vinsmoke Sanji', 'Black Leg', 4, 1032000000, 'Active', 'Defeating Queen / Germa Science', 'Post-Wano', 1058, 'Straw Hat Pirates', 'The "Wings" of the Pirate King.'),
(NULL, 'Jack', 'The Drought', 1, 1000000000, 'Active', 'Destruction of Zou / Kaido''s Commander', 'Zou', 809, 'Beasts Pirates', 'First 1B bounty revealed.'),
(NULL, 'Charlotte Smoothie', 'Juice Minister', 1, 932000000, 'Active', 'Big Mom Sweet Commander', 'WCI', 846, 'Big Mom Pirates', 'Hybrid long-leg tribe.'),
(NULL, 'Nico Robin', 'Devil Child', 1, 79000000, 'Active (Updated)', 'Survivor of Ohara', 'Water 7', 398, 'Straw Hat Pirates', 'Assigned at age 8.'),
(NULL, 'Nico Robin', 'Devil Child', 2, 80000000, 'Active (Updated)', 'Enies Lobby participation', 'Post-Enies Lobby', 435, 'Straw Hat Pirates', 'Minimal increase.'),
(NULL, 'Nico Robin', 'Devil Child', 3, 130000000, 'Active (Updated)', 'Dressrosa participation', 'Post-Dressrosa', 801, 'Straw Hat Pirates', 'Defeated Gladius (assist).'),
(NULL, 'Nico Robin', 'Devil Child', 4, 930000000, 'Active', 'Defeating Black Maria / Reading Poneglyphs', 'Post-Wano', 1058, 'Straw Hat Pirates', 'Massive threat to World Govt.'),
(NULL, 'Charlotte Cracker', 'Biscuit Knight', 1, 860000000, 'Active', 'Big Mom Sweet Commander', 'WCI', 836, 'Big Mom Pirates', 'Defeated by Luffy/Nami.'),
(NULL, 'Charlotte Perospero', 'Candy Minister', 1, 700000000, 'Active', 'Eldest Son of Big Mom', 'WCI', 834, 'Big Mom Pirates', 'Defeated by Nekomamushi.'),
(NULL, 'Sabo', 'Flame Emperor', 1, 602000000, 'Active', 'Chief of Staff Revolutionary Army', 'Dressrosa', 794, 'Revolutionary Army', 'Number 2 of Revolutionaries.'),
(NULL, 'Charlotte Snack', NULL, 1, 600000000, 'Active', 'Former Sweet Commander', 'WCI', 837, 'Big Mom Pirates', 'Demoted after loss to Urouge.'),
(NULL, 'Little Oars Jr.', NULL, 1, 550000000, 'Active', 'Marineford Invasion', 'Marineford', 554, 'Whitebeard Allies', 'Ancient Giant descendant.'),
(NULL, 'Portgas D. Ace', 'Fire Fist', 1, 550000000, 'Inactive (Deceased)', 'Commander 2nd Division / Roger''s Son', 'Marineford', 552, 'Whitebeard Pirates', 'Captured by Blackbeard.'),
(NULL, 'Who''s Who', 'The Droplet', 1, 546000000, 'Active', 'Tobi Roppo / Former CP9', 'Wano Country', 978, 'Beasts Pirates', 'Knows Gum-Gum Fruit secret.'),
(NULL, 'Don Chinjao', 'The Drill', 1, 542000000, 'Active', 'Legendary Pirate', 'Dressrosa', 708, 'Happo Navy', 'Rival to Garp.'),
(NULL, 'Izou', NULL, 1, 510000000, 'Inactive (Deceased)', 'Whitebeard Commander / Wano Retainer', 'Wano Country', 957, 'Whitebeard Pirates', 'Died fighting CP0.'),
(NULL, 'Koby', 'The Hero', 1, 500000000, 'Active', 'Cross Guild Marine Bounty (5 Stars)', 'Egghead', 1056, 'Marines', 'Sword Member / Hero of Rocky Port.'),
(NULL, 'Usopp', 'Sogeking', 1, 30000000, 'Active (Updated)', 'Enies Lobby / Burning Flag', 'Post-Enies Lobby', 435, 'Straw Hat Pirates', 'Alter ego used.'),
(NULL, 'Usopp', 'God Usopp', 2, 200000000, 'Active (Updated)', 'Dressrosa / Snipping Sugar', 'Post-Dressrosa', 801, 'Straw Hat Pirates', 'Identified as God Usopp.'),
(NULL, 'Usopp', 'God Usopp', 3, 500000000, 'Active', 'Wano Raid participation', 'Post-Wano', 1058, 'Straw Hat Pirates', 'Credit for pageantry.'),
(NULL, 'Black Maria', NULL, 1, 480000000, 'Active', 'Tobi Roppo', 'Wano Country', 978, 'Beasts Pirates', 'Defeated by Robin.'),
(NULL, 'Edward Weevil', 'Whitebeard Jr.', 1, 480000000, 'Active', 'Former Warlord / Aggression', 'Zou', 802, 'Independent', 'Claims to be WB''s son.'),
(NULL, 'Sasaki', NULL, 1, 472000000, 'Active', 'Tobi Roppo / Armored Division', 'Wano Country', 978, 'Beasts Pirates', 'Defeated by Franky.'),
(NULL, 'Belo Betty', NULL, 1, 457000000, 'Active', 'Revolutionary Army Commander (East)', 'Reverie', 904, 'Revolutionary Army', 'Inspires citizens.'),
(NULL, 'Tamago', 'Baron', 1, 429000000, 'Active', 'Combatant Knight', 'WCI', 829, 'Big Mom Pirates', 'Long-leg tribe.'),
(NULL, 'Karasu', NULL, 1, 400000000, 'Active', 'Revolutionary Army Commander (North)', 'Reverie', 904, 'Revolutionary Army', 'Soot-Soot Fruit user.'),
(NULL, 'Ulti', NULL, 1, 400000000, 'Active', 'Tobi Roppo', 'Wano Country', 978, 'Beasts Pirates', 'Defeated by Nami/Zeus.'),
(NULL, 'Franky', 'Cyborg', 1, 44000000, 'Active (Updated)', 'Enies Lobby / Burning Blueprint', 'Post-Enies Lobby', 435, 'Straw Hat Pirates', 'Battle Franky 37.'),
(NULL, 'Franky', 'Cyborg', 2, 94000000, 'Active (Updated)', 'Dressrosa / Defeating Senor Pink', 'Post-Dressrosa', 801, 'Straw Hat Pirates', 'General Franky used.'),
(NULL, 'Franky', 'Cyborg', 3, 394000000, 'Active', 'Defeating Sasaki', 'Post-Wano', 1058, 'Straw Hat Pirates', 'Poster is of the Thousand Sunny.'),
(NULL, 'Brook', 'Soul King', 1, 33000000, 'Active (Updated)', 'Rumbar Pirates past', 'Thriller Bark', 489, 'Straw Hat Pirates', 'Active from 50 years ago.'),
(NULL, 'Brook', 'Soul King', 2, 83000000, 'Active (Updated)', 'Dressrosa / Fame as Soul King', 'Post-Dressrosa', 801, 'Straw Hat Pirates', 'Concert poster used.'),
(NULL, 'Brook', 'Soul King', 3, 383000000, 'Active', 'WCI Poneglyph Heist / Wano Assist', 'Post-Wano', 1058, 'Straw Hat Pirates', 'MVP of WCI.'),
(NULL, 'Pedro', 'Of the Treetops', 1, 382000000, 'Inactive (Deceased)', 'Nox Pirates Captain', 'WCI', 834, 'Minks / Nox Pirates', 'Suicide bombing vs Perospero.'),
(NULL, 'Nami', 'Cat Burglar', 1, 16000000, 'Active (Updated)', 'Enies Lobby / Defeating Kalifa', 'Post-Enies Lobby', 435, 'Straw Hat Pirates', 'Sexualized poster requested by photographer.'),
(NULL, 'Nami', 'Cat Burglar', 2, 66000000, 'Active (Updated)', 'Dressrosa participation', 'Post-Dressrosa', 801, 'Straw Hat Pirates', 'Minor increase.'),
(NULL, 'Nami', 'Cat Burglar', 3, 366000000, 'Active', 'Defeating Ulti (with Big Mom''s help)', 'Post-Wano', 1058, 'Straw Hat Pirates', 'Possesses Zeus.'),
(NULL, 'Capone Bege', 'Gang', 1, 138000000, 'Active (Updated)', 'West Blue Mafia history', 'Sabaody', 498, 'Fire Tank Pirates', 'Supernova.'),
(NULL, 'Capone Bege', 'Gang', 2, 300000000, 'Active (Updated)', 'Big Mom assassination attempt', 'WCI', 857, 'Fire Tank Pirates', 'Married Chiffon.'),
(NULL, 'Capone Bege', 'Gang', 3, 350000000, 'Active', 'Post-WCI escape', 'Post-WCI', 903, 'Fire Tank Pirates', 'Cover story adventures.'),
(NULL, 'Donquixote Doflamingo', 'Heavenly Yaksha', 1, 340000000, 'Frozen (Captured)', 'Former Warlord / King of Dressrosa', 'Jaya', 233, 'Donquixote Family', 'Rules the underworld as Joker.'),
(NULL, 'Cavendish', 'White Horse', 1, 280000000, 'Active (Updated)', 'Super Rookie', 'Dressrosa', 704, 'Beautiful Pirates', 'Has split personality Hakuba.'),
(NULL, 'Cavendish', 'White Horse', 2, 330000000, 'Active', 'Straw Hat Grand Fleet', 'Post-Dressrosa', 801, 'Straw Hat Grand Fleet', '1st Ship Captain.'),
(NULL, 'Pekoms', NULL, 1, 330000000, 'Active (Status Unknown)', 'Combatant', 'Fishman Island', 651, 'Big Mom Pirates', 'Mink tribe.'),
(NULL, 'Gecko Moria', NULL, 1, 320000000, 'Active', 'Former Warlord', 'Thriller Bark', 455, 'Thriller Bark Pirates', 'Rival to Kaido in past.'),
(NULL, 'Basil Hawkins', 'Magician', 1, 249000000, 'Active (Updated)', 'North Blue Pirate', 'Sabaody', 498, 'Hawkins Pirates', 'Supernova.'),
(NULL, 'Basil Hawkins', 'Magician', 2, 320000000, 'Inactive (Deceased?)', 'Wano Headliner', 'Post-Timeskip', 601, 'Beasts Pirates', 'Died in Wano war.'),
(NULL, 'Lindbergh', NULL, 1, 316000000, 'Active', 'Revolutionary Army Commander (South)', 'Reverie', 904, 'Revolutionary Army', 'Mink inventor.'),
(NULL, 'Jewelry Bonney', 'Big Eater', 1, 140000000, 'Active (Updated)', 'South Blue Pirate', 'Sabaody', 498, 'Bonney Pirates', 'Supernova.'),
(NULL, 'Jewelry Bonney', 'Big Eater', 2, 320000000, 'Active', 'Reverie infiltration / Egghead', 'Egghead', 1060, 'Bonney Pirates', 'Daughter of Kuma.'),
(NULL, 'Caesar Clown', 'Master', 1, 300000000, 'Active', 'Mass Murder weapon expert', 'Punk Hazard', 664, 'Donquixote Affiliate', 'Former MADS scientist.'),
(NULL, 'Charlotte Oven', 'Browned', 1, 300000000, 'Active', 'Minister of Baking', 'WCI', 861, 'Big Mom Pirates', 'Heat-Heat Fruit.'),
(NULL, 'Charlotte Daifuku', 'Bean', 1, 300000000, 'Active', 'Minister of Beans', 'WCI', 861, 'Big Mom Pirates', 'Genie user.'),
(NULL, 'Bartholomew Kuma', 'Tyrant', 1, 296000000, 'Frozen (Deceased/Robot)', 'Former Warlord / Revolutionary', 'Jaya', 233, 'Revolutionary Army', 'Turned into Pacifista.'),
(NULL, 'Morley', NULL, 1, 293000000, 'Active', 'Revolutionary Army Commander (West)', 'Reverie', 904, 'Revolutionary Army', 'Giant / Okama.'),
(NULL, 'Page One', NULL, 1, 290000000, 'Active', 'Tobi Roppo', 'Wano Country', 929, 'Beasts Pirates', 'Spinosaurus user.'),
(NULL, 'Fisher Tiger', NULL, 1, 230000000, 'Inactive (Deceased)', 'Assault on Mary Geoise', 'Fishman Island', 620, 'Sun Pirates', 'Freed the slaves.'),
(NULL, 'X Drake', 'Red Flag', 1, 222000000, 'Active', 'Marine Spy (SWORD)', 'Sabaody', 498, 'Drake Pirates / Marines', 'Undercover as pirate.'),
(NULL, 'Sai', 'Don', 1, 210000000, 'Active', 'Leader of Happo Navy', 'Post-Dressrosa', 801, 'Straw Hat Grand Fleet', '3rd Ship Captain.'),
(NULL, 'Squard', 'Maelstrom Spider', 1, 210000000, 'Active', 'Whitebeard Ally', 'Marineford', 555, 'Squard Pirates', 'Manipulated by Akainu.'),
(NULL, 'Caribou', 'Wet-Haired', 1, 210000000, 'Active', 'Rookie Killer', 'Return to Sabaody', 600, 'Caribou Pirates', 'Knows Ancient Weapon locations.'),
(NULL, 'Scratchmen Apoo', 'Roar of the Sea', 1, 198000000, 'Active (Updated)', 'Longarm Tribe Pirate', 'Sabaody', 498, 'On Air Pirates', 'Supernova.'),
(NULL, 'Scratchmen Apoo', 'Roar of the Sea', 2, 350000000, 'Active', 'Kaido Informant', 'Post-Timeskip', 601, 'On Air Pirates', 'Betrayed Kid/Hawkins.'),
(NULL, 'Killer', 'Massacre Soldier', 1, 162000000, 'Active (Updated)', 'Kid''s Vice Captain', 'Sabaody', 498, 'Kid Pirates', 'Supernova (Non-Captain).'),
(NULL, 'Killer', 'Massacre Soldier', 2, 200000000, 'Active', 'Wano participation / Kamazo', 'Post-Timeskip', 601, 'Kid Pirates', 'Failed SMILE eater.'),
(NULL, 'Bartolomeo', 'Cannibal', 1, 150000000, 'Active (Updated)', 'Rookie', 'Dressrosa', 704, 'Barto Club', 'Luffy Fanboy.'),
(NULL, 'Bartolomeo', 'Cannibal', 2, 200000000, 'Active', 'Straw Hat Grand Fleet', 'Post-Dressrosa', 801, 'Straw Hat Grand Fleet', '2nd Ship Captain.'),
(NULL, 'Bellamy', 'The Hyena', 1, 55000000, 'Active (Updated)', 'Mock Town bully', 'Jaya', 222, 'Bellamy Pirates', 'Mocked Luffy.'),
(NULL, 'Bellamy', 'The Hyena', 2, 195000000, 'Retired', 'Doflamingo Officer', 'Dressrosa', 706, 'Donquixote Family', 'Retired to dye flags.'),
(NULL, 'Coribou', NULL, 1, 190000000, 'Active', 'Caribou''s Brother', 'Return to Sabaody', 600, 'Caribou Pirates', 'Comparison to lizard.'),
(NULL, 'Orlumbus', 'Massacre Ruler', 1, 148000000, 'Active', 'Yonta Maria Fleet Admiral', 'Post-Dressrosa', 801, 'Straw Hat Grand Fleet', '7th Ship Captain.'),
(NULL, 'Charlotte Mont-d''Or', 'Scribe', 1, 120000000, 'Active', 'Minister of Cheese', 'WCI', 829, 'Big Mom Pirates', 'Book fruit.'),
(NULL, 'Urouge', 'Mad Monk', 1, 108000000, 'Active', 'Sky Island Pirate', 'Sabaody', 498, 'Fallen Monk Pirates', 'Defeated Snack (600M).'),
(NULL, 'Bobbin', NULL, 1, 105500000, 'Active', 'Bishop Combatant', 'WCI', 829, 'Big Mom Pirates', 'Fixer for Big Mom.'),
(NULL, 'Dorry', 'Blue Ogre', 1, 100000000, 'Active (Updated)', 'Little Garden Duel', 'Little Garden', 118, 'Giant Warrior Pirates', '100 year old bounty.'),
(NULL, 'Dorry', 'Blue Ogre', 2, 1800000000, 'Active', 'Egghead Raid / Shanks Ally', 'Egghead', 1110, 'Giant Warrior Pirates', 'Major update.'),
(NULL, 'Brogy', 'Red Ogre', 1, 100000000, 'Active (Updated)', 'Little Garden Duel', 'Little Garden', 118, 'Giant Warrior Pirates', '100 year old bounty.'),
(NULL, 'Brogy', 'Red Ogre', 2, 1800000000, 'Active', 'Egghead Raid / Shanks Ally', 'Egghead', 1110, 'Giant Warrior Pirates', 'Major update.'),
(NULL, 'Vito', 'Monster Gun', 1, 95000000, 'Active', 'Bege''s Advisor', 'Zou', 813, 'Fire Tank Pirates', 'Large hands.'),
(NULL, 'Rockstar', NULL, 1, 94000000, 'Active', 'New Recruit', 'Jaya', 234, 'Red Hair Pirates', 'Messenger to Whitebeard.'),
(NULL, 'Gasparde', NULL, 1, 95000000, 'Active (Non-Canon)', 'Dead End Adventure Movie', 'Movie 4', N/A, 'Gasparde Pirates', 'Logia Candy.'),
(NULL, 'Gotti', 'Assassin', 1, 90000000, 'Active', 'Bege''s Hitman', 'Zou', 813, 'Fire Tank Pirates', 'Cyborg arm.'),
(NULL, 'Lip Doughty', NULL, 1, 88000000, 'Active', 'Sabaody Rookie', 'Return to Sabaody', 600, 'Unknown', 'Joined Fake Straw Hats.'),
(NULL, 'Brownbeard', NULL, 1, 80060000, 'Active', 'Punk Hazard Patrol', 'Punk Hazard', 664, 'Brownbeard Pirates', 'Centaur form.'),
(NULL, 'Mr. 1', 'Daz Bonez', 1, 75000000, 'Active', 'Baroque Works Agent', 'Alabasta', 190, 'Baroque Works / Cross Guild', 'Joined Crocodile.'),
(NULL, 'Gyro', 'Crab-Hand', 1, 73000000, 'Active', 'Fishman Island Intruder', 'Fishman Island', 611, 'Gyro Pirates', 'Eaten by Hody Jones'' crew.'),
(NULL, 'Doc Q', 'Death God', 1, 72000000, 'Active', 'Blackbeard Doctor', 'Jaya', 234, 'Blackbeard Pirates', 'Sickly horse Stronger.'),
(NULL, 'Gambit', NULL, 1, 67000000, 'Active', 'Capone''s Staff', 'Sabaody', 498, 'Fire Tank Pirates', 'Unknown fate.'),
(NULL, 'Suleiman', 'The Beheader', 1, 67000000, 'Active', 'Criminal of War', 'Dressrosa', 704, 'Straw Hat Grand Fleet', 'Joined Cavendish.'),
(NULL, 'Lao G', NULL, 1, 61000000, 'Frozen (Captured)', 'Donquixote Executive', 'Dressrosa', 702, 'Donquixote Family', 'G-Style martial arts.'),
(NULL, 'Devil Dias', NULL, 1, 60000000, 'Inactive', 'Slave', 'Sabaody', 497, 'Acumate Pirates', 'Collared by Tenryuubito.'),
(NULL, 'Senor Pink', NULL, 1, 58000000, 'Frozen (Captured)', 'Donquixote Executive', 'Dressrosa', 702, 'Donquixote Family', 'Hard-boiled.'),
(NULL, 'Kelly Funk', NULL, 1, 57000000, 'Active', 'Assassin', 'Dressrosa', 704, 'Funk Brothers', 'Jacket Fruit.'),
(NULL, 'Byrnndi World', 'World Destroyer', 1, 500000000, 'Active (Non-Canon)', '3D2Y Special', 'TV Special', N/A, 'World Pirates', 'Moa Moa Fruit.'),
(NULL, 'Peachbeard', NULL, 1, 52000000, 'Active', 'Blackbeard Affiliate', 'Reverie', 904, 'Peachbeard Pirates', 'Attacked Lulusia.'),
(NULL, 'Roshio', ' The Executioner', 1, 42000000, 'Inactive (Deceased)', 'Mock Town Victim', 'Jaya', 222, 'Roshio Pirates', 'Killed by Bellamy.'),
(NULL, 'Sarkies', 'Big Knife', 1, 38000000, 'Active', 'Bellamy''s Mate', 'Jaya', 222, 'Bellamy Pirates', 'Mind-controlled by Doflamingo.'),
(NULL, 'Shoujou', 'Sonar King', 1, 36000000, 'Active', 'Salvage King', 'Jaya', 226, 'Saruyama Alliance', 'Looks like a monkey.'),
(NULL, 'Mikazuki', NULL, 1, 36000000, 'Active', 'Water 7 Bully', 'Water 7', 323, 'Big Helmet Pirates', 'Beaten by Galley-La.'),
(NULL, 'Bobby Funk', NULL, 1, 36000000, 'Active', 'Assassin', 'Dressrosa', 704, 'Funk Brothers', 'Wears Kelly (Jacket).'),
(NULL, 'Miss Doublefinger', 'Zala', 1, 35000000, 'Active', 'Baroque Works Agent', 'Alabasta', 190, 'Baroque Works', 'Spike Fruit.'),
(NULL, 'Mr. 2', 'Bon Kurei', 1, 32000000, 'Active (Impel Down)', 'Baroque Works Agent', 'Alabasta', 156, 'Baroque Works', 'New Queen of Newkama Land.'),
(NULL, 'Gladius', NULL, 1, 31000000, 'Frozen (Captured)', 'Donquixote Officer', 'Dressrosa', 702, 'Donquixote Family', 'Pop-Pop Fruit.'),
(NULL, 'Miss Goldenweek', 'Marianne', 1, 29000000, 'Active', 'Baroque Works Agent', 'Little Garden', 117, 'Baroque Works', 'Colors Trap user.'),
(NULL, 'Demaro Black', 'Three-Tongued', 1, 26000000, 'Active', 'Impersonator', 'Return to Sabaody', 600, 'Fake Straw Hat Pirates', 'Posed as Luffy.'),
(NULL, 'Mont Blanc Cricket', NULL, 1, 25000000, 'Active', 'Liar Noland Descendant', 'Jaya', 226, 'Saruyama Alliance', 'Looking for Golden City.'),
(NULL, 'Galdino', 'Mr. 3', 1, 24000000, 'Active', 'Baroque Works Agent', 'Little Garden', 117, 'Cross Guild', 'Wax-Wax Fruit.'),
(NULL, 'Foxy', 'Silver Fox', 1, 24000000, 'Active', 'Davy Back Fight', 'Long Ring Long Land', 305, 'Foxy Pirates', 'Slow-Slow Fruit.'),
(NULL, 'Masira', 'Salvage King', 1, 23000000, 'Active', 'Salvage King', 'Jaya', 220, 'Saruyama Alliance', 'Monkey appearance.'),
(NULL, 'Arlong', 'The Saw', 1, 20000000, 'Active', 'East Blue Tyrant', 'Arlong Park', 69, 'Arlong Pirates', 'Bribed Marines to stay hidden.'),
(NULL, 'Don Krieg', 'Foul Play', 1, 17000000, 'Active', 'East Blue Overlord', 'Baratie', 46, 'Krieg Pirates', 'Commanded 50 ships.'),
(NULL, 'Lacuba', NULL, 1, 17000000, 'Active', 'Slave', 'Sabaody', 500, 'Unknown', 'Pirate Strategist.'),
(NULL, 'Kuro', 'Clahador', 1, 16000000, 'Active', 'Black Cat Captain', 'Syrup Village', 26, 'Black Cat Pirates', 'Faked death.'),
(NULL, 'Wellington', NULL, 1, 10000000, 'Active', 'Enies Lobby Guard', 'Enies Lobby', 426, 'None', 'Only anime filler bounty.'),
(NULL, 'Dick', NULL, 1, 10000000, 'Active', 'Mountain Bandit', 'Post-War', 584, 'Bandit', 'Beaten by Ace/Sabo.'),
(NULL, 'Machvise', NULL, 1, 11000000, 'Frozen (Captured)', 'Donquixote Officer', 'Dressrosa', 702, 'Donquixote Family', 'Ton-Ton Fruit.'),
(NULL, 'Gin', 'Man-Demon', 1, 12000000, 'Active (Unknown)', 'Krieg Combatant', 'Baratie', 46, 'Krieg Pirates', 'Refused to kill Sanji.'),
(NULL, 'Higuma', 'The Bear', 1, 8000000, 'Inactive (Deceased)', 'Mountain Bandit', 'Romance Dawn', 1, 'Bandit', 'Killed by Sea King.'),
(NULL, 'Curly Dadan', NULL, 1, 7800000, 'Active', 'Mountain Bandit', 'Post-War', 584, 'Dadan Family', 'Foster mother to Ace/Luffy.'),
(NULL, 'Bluejam', NULL, 1, 14300000, 'Inactive', 'East Blue Pirate', 'Post-War', 584, 'Bluejam Pirates', 'Burned in Gray Terminal.'),
(NULL, 'Golass', NULL, 1, 8000000, 'Active', 'Sniper Island Enemy', 'Filler', N/A, 'Unknown', 'Anime only.'),
(NULL, 'Miss Valentine', 'Mikita', 1, 7500000, 'Active', 'Baroque Works Agent', 'Whiskey Peak', 112, 'Baroque Works', 'Kilo-Kilo Fruit.'),
(NULL, 'Sham', NULL, 1, 7000000, 'Active', 'Black Cat Officer', 'Syrup Village', 32, 'Black Cat Pirates', 'Nyaban Brothers.'),
(NULL, 'Buchi', NULL, 1, 7000000, 'Active', 'Black Cat Officer', 'Syrup Village', 32, 'Black Cat Pirates', 'Nyaban Brothers.'),
(NULL, 'Jango', 'Double-Crosser', 1, 9000000, 'Revoked', 'Black Cat Hypnotist', 'Syrup Village', 26, 'Marines', 'Joined Marines under Hina.'),
(NULL, 'Alvida', 'Iron Mace', 1, 5000000, 'Active', 'East Blue Pirate', 'Romance Dawn', 2, 'Cross Guild', 'First villain.'),
(NULL, 'Porchemy', NULL, 1, 34000000, 'Inactive (Deceased)', 'Bluejam Officer', 'Post-War', 584, 'Bluejam Pirates', 'Tortured Luffy.'),
(NULL, 'Babe', 'Mr. 4', 1, 3200000, 'Active', 'Baroque Works Agent', 'Alabasta', 163, 'Baroque Works', 'Dog-Gun Lassoo.'),
(NULL, 'Bepo', NULL, 1, 500, 'Active', 'Heart Pirates Navigator', 'Sabaody', 498, 'Heart Pirates', 'Mistaken for pet.'),
(NULL, 'Tony Tony Chopper', 'Cotton Candy Lover', 1, 50, 'Active (Updated)', 'Enies Lobby', 'Post-Enies Lobby', 435, 'Straw Hat Pirates', 'Mistaken for pet.'),
(NULL, 'Tony Tony Chopper', 'Cotton Candy Lover', 2, 100, 'Active (Updated)', 'Dressrosa', 'Post-Dressrosa', 801, 'Straw Hat Pirates', 'Still a pet.'),
(NULL, 'Tony Tony Chopper', 'Cotton Candy Lover', 3, 1000, 'Active', 'Wano Raid', 'Post-Wano', 1058, 'Straw Hat Pirates', '10x increase (still low).'),
(NULL, 'Pandaman', NULL, 1, 3333333, 'Active', 'Easter Egg', 'Recurring', N/A, 'None', 'Joke character.'),
(NULL, 'Charlotte Perespero', 'ERROR', 1, 700000000, 'Duplicate', NULL, NULL, NULL, NULL, 'Duplicate entry for check.'),
(NULL, 'Vista', 'Flower Sword', 1, 0, 'Active (Unknown)', 'Whitebeard Commander', 'Marineford', 553, 'Whitebeard Pirates', 'Rivaled Mihawk.'),
(NULL, 'Jozu', 'Diamond', 1, 0, 'Active (Unknown)', 'Whitebeard Commander', 'Marineford', 553, 'Whitebeard Pirates', 'Lost arm to Aokiji.'),
(NULL, 'Lucky Roux', NULL, 1, 0, 'Active (Unknown)', 'Red Hair Officer', 'Romance Dawn', 1, 'Red Hair Pirates', 'Fastest shooter.'),
(NULL, 'Benn Beckman', NULL, 1, 0, 'Active (Unknown)', 'Red Hair Vice Captain', 'Romance Dawn', 1, 'Red Hair Pirates', 'Comparable to Shanks.'),
(NULL, 'Yasopp', 'Chaser', 1, 0, 'Active (Unknown)', 'Red Hair Sniper', 'Romance Dawn', 1, 'Red Hair Pirates', 'Usopp''s dad.'),
(NULL, 'Dellinger', NULL, 1, 15000000, 'Frozen (Captured)', 'Donquixote Officer', 'Dressrosa', 702, 'Donquixote Family', 'Fighting fish hybrid.'),
(NULL, 'Baby 5', NULL, 1, 0, 'Active (Retired)', 'Former Donquixote', 'Dressrosa', 702, 'Happo Navy', 'Married Sai.'),
(NULL, 'Buffalo', NULL, 1, 0, 'Active', 'Donquixote Officer', 'Punk Hazard', 692, 'Donquixote Family', 'Spin-Spin Fruit.'),
(NULL, 'Sugar', NULL, 1, 0, 'Frozen (Captured)', 'Donquixote Special Officer', 'Dressrosa', 702, 'Donquixote Family', 'Hobi Hobi Fruit (Toys).'),
(NULL, 'Trebol', NULL, 1, 99000000, 'Frozen (Captured)', 'Donquixote Elite', 'Dressrosa', 702, 'Donquixote Family', 'Sticky-Sticky Fruit.'),
(NULL, 'Diamante', NULL, 1, 99000000, 'Frozen (Captured)', 'Donquixote Elite', 'Dressrosa', 702, 'Donquixote Family', 'Flag-Flag Fruit.'),
(NULL, 'Pica', NULL, 1, 99000000, 'Frozen (Captured)', 'Donquixote Elite', 'Dressrosa', 702, 'Donquixote Family', 'Stone-Stone Fruit.'),
(NULL, 'Gecko Moria', NULL, 1, 320000000, 'Active', 'Thriller Bark', 'Thriller Bark', 455, 'Thriller Bark Pirates', 'Shadow Fruit.'),
(NULL, 'Jaguar D. Saul', NULL, 1, 0, 'Inactive (Hiding?)', 'Former Vice Admiral', 'Ohara', 392, 'Marines', 'Frozen by Aokiji.'),
(NULL, 'Kuzan', 'Aokiji', 1, 3000000000, 'Active', 'Cross Guild Marine Bounty (Estimate)', 'Egghead', 1056, 'Blackbeard Pirates', 'Former Admiral turned Pirate.'),
(NULL, 'Sakazuki', 'Akainu', 1, 3000000000, 'Active', 'Cross Guild Marine Bounty (Estimate)', 'Egghead', 1056, 'Marines', 'Fleet Admiral (likely higher).'),
(NULL, 'Borsalino', 'Kizaru', 1, 3000000000, 'Active', 'Cross Guild Marine Bounty (Estimate)', 'Egghead', 1056, 'Marines', 'Admiral.'),
(NULL, 'Hibari', NULL, 1, 200000000, 'Active', 'Cross Guild Marine Bounty (2 Stars)', 'Egghead', 1080, 'Marines', 'SWORD member.'),
(NULL, 'Prince Grus', NULL, 1, 500000000, 'Active', 'Cross Guild Marine Bounty (5 Stars)', 'Egghead', 1080, 'Marines', 'SWORD member.'),
(NULL, 'Kujaku', NULL, 1, 500000000, 'Active', 'Cross Guild Marine Bounty (5 Stars)', 'Egghead', 1080, 'Marines', 'SWORD member / Tsuru''s granddaughter.'),
(NULL, 'Silvers Rayleigh', 'Dark King', 1, 0, 'Active (Unknown)', 'Roger''s First Mate / Knows Void Century', 'Sabaody', 500, 'Roger Pirates', 'Bounty is active but amount unrevealed (likely Billions).'),
(NULL, 'Douglas Bullet', 'Demon Heir', 1, 4428000000, 'Active (Non-Canon)', 'Stampede Movie Villain', 'Movie Stampede', N/A, 'Roger Pirates / Independent', 'Rivaled Roger in strength.'),
(NULL, 'Shiki', 'Golden Lion', 1, 0, 'Active (Unknown)', 'First Impel Down escapee / Rival to Roger', 'Strong World', 0, 'Golden Lion Pirates', 'Declared war on World Govt 20 years ago.'),
(NULL, 'T-Bone', 'Ship Cutter', 1, 500000000, 'Inactive (Deceased)', 'Cross Guild Marine Bounty (5 Stars)', 'Egghead', 1082, 'Marines', 'Killed by a starving civilian for the bounty.'),
(NULL, 'Hajrudin', 'Pirate Mercenary', 1, 230000000, 'Active', 'New Giant Warrior Pirates Captain', 'Post-Dressrosa', 801, 'Straw Hat Grand Fleet', '6th Ship Captain.'),
(NULL, 'Ideo', 'Destruction Cannon', 1, 195000000, 'Active', 'XXX Gym Martial Arts Alliance', 'Post-Dressrosa', 801, 'Straw Hat Grand Fleet', '4th Ship Captain / Longarm Tribe.'),
(NULL, 'Leo', 'Warrior', 1, 79000000, 'Active', 'Tontatta Pirates Captain', 'Post-Dressrosa', 801, 'Straw Hat Grand Fleet', '5th Ship Captain / Tontatta Tribe.'),
(NULL, 'Blue Gilly', NULL, 1, 160000000, 'Active', 'Jiaokune Do Master', 'Post-Dressrosa', 801, 'Straw Hat Grand Fleet', 'Joined Ideo''s crew / Longleg Tribe.'),
(NULL, 'Abdullah', NULL, 1, 0, 'Active (Unknown)', 'Criminal', 'Dressrosa', 704, 'Straw Hat Grand Fleet', 'Joined Ideo / Former Bounty Hunter.'),
(NULL, 'Jeet', NULL, 1, 0, 'Active (Unknown)', 'Criminal', 'Dressrosa', 704, 'Straw Hat Grand Fleet', 'Joined Ideo / Former Bounty Hunter.'),
(NULL, 'Albion', 'Gashed', 1, 92000000, 'Active', 'Sabaody Recruit', 'Return to Sabaody', 600, 'Unknown', 'Attempted to join Fake Straw Hats.'),
(NULL, 'Rock', 'Yeti Cool Brother', 1, 20000000, 'Active', 'Assassin', 'Punk Hazard', 666, 'Unknown', 'Worked for Caesar Clown.'),
(NULL, 'Scotch', 'Yeti Cool Brother', 1, 20000000, 'Active', 'Assassin', 'Punk Hazard', 666, 'Unknown', 'Worked for Caesar Clown.'),
(NULL, 'Hyouzou', 'Drunkard', 1, 0, 'Active (Unknown)', 'Mercenary Swordsman', 'Fishman Island', 609, 'New Fishman Pirates', 'Blue-ringed octopus merman.'),
(NULL, 'Dosun', NULL, 1, 0, 'Active (Unknown)', 'Officer', 'Fishman Island', 611, 'New Fishman Pirates', 'Hammerhead shark fishman.'),
(NULL, 'Zeo', NULL, 1, 0, 'Active (Unknown)', 'Officer', 'Fishman Island', 611, 'New Fishman Pirates', 'Wobbegong shark fishman.'),
(NULL, 'Daruma', NULL, 1, 0, 'Active (Unknown)', 'Officer', 'Fishman Island', 611, 'New Fishman Pirates', 'Cookie-cutter shark fishman.'),
(NULL, 'Ikaros Much', NULL, 1, 0, 'Active (Unknown)', 'Officer', 'Fishman Island', 611, 'New Fishman Pirates', 'Giant squid fishman.'),
(NULL, 'Vander Decken IX', NULL, 1, 0, 'Frozen (Captured)', 'Flying Pirates Captain', 'Fishman Island', 606, 'Flying Pirates', 'Stalked Shirahoshi.'),
(NULL, 'Caribou', 'Wet-Haired', 2, 210000000, 'Active', 'Wano Information', 'Wano Country', 940, 'Caribou Pirates', 'Tried to join Straw Hats.'),
(NULL, 'Coribou', NULL, 2, 190000000, 'Active', 'Wano Cover Story', 'Wano Country', 940, 'Caribou Pirates', 'Rescued brother.'),
(NULL, 'Gambia', 'The Missionary', 1, 67000000, 'Active', 'Barto Club Staff', 'Dressrosa', 705, 'Barto Club', 'Bartolomeo''s subordinate.'),
(NULL, 'Suleiman', 'The Beheader', 1, 67000000, 'Active', 'Class A War Criminal', 'Dressrosa', 704, 'Beautiful Pirates', 'Joined Cavendish.'),
(NULL, 'Puzzle', 'Phoenix', 1, 100000000, 'Active (Non-Canon)', 'Ice Hunter Arc', 'Anime Filler', 326, 'Phoenix Pirates', 'New World survivor.'),
(NULL, 'Mad Treasure', NULL, 1, 200000000, 'Active (Non-Canon)', 'Heart of Gold Special', 'TV Special', N/A, 'Treasure Pirates', 'Chain-Chain Fruit.'),
(NULL, 'Psycho P', NULL, 1, 200000000, 'Active (Non-Canon)', 'Heart of Gold Special', 'TV Special', N/A, 'Treasure Pirates', 'Camo-Camo Fruit.'),
(NULL, 'Bill', 'Smelter', 1, 10000000, 'Active (Non-Canon)', 'Silver Mine Arc', 'Anime Filler', 746, 'Silver Pirate Alliance', 'Smelt-Smelt Fruit.'),
(NULL, 'Peseta', NULL, 1, 6000000, 'Active (Non-Canon)', 'Silver Mine Arc', 'Anime Filler', 746, 'Silver Pirate Alliance', 'Bill''s subordinate.'),
(NULL, 'Desire', NULL, 1, 5000000, 'Active (Non-Canon)', 'Silver Mine Arc', 'Anime Filler', 746, 'Silver Pirate Alliance', 'Bartolomeo''s childhood friend.'),
(NULL, 'Gild Tesoro', 'Golden Emperor', 1, 0, 'Active (Unknown - Non-Canon)', 'Film Gold Villain', 'Movie Gold', N/A, 'Tesoro Crew', 'Possesses 20% of world''s berries.'),
(NULL, 'Charlotte Galette', NULL, 1, 0, 'Active (Unknown)', 'Minister of Butter', 'WCI', 829, 'Big Mom Pirates', '18th Daughter.'),
(NULL, 'Charlotte Opera', NULL, 1, 0, 'Active (Unknown)', 'Minister of Whipped Cream', 'WCI', 829, 'Big Mom Pirates', '5th Son.'),
(NULL, 'Charlotte Amande', 'Demon Lady', 1, 0, 'Active (Unknown)', 'Minister of Nuts', 'WCI', 829, 'Big Mom Pirates', 'Swordsman "Slow Ballad".'),
(NULL, 'Bobbin', ' The Disposer', 1, 105500000, 'Active', 'Bishop Rank', 'WCI', 829, 'Big Mom Pirates', 'Fixer.'),
(NULL, 'Diesel', NULL, 1, 0, 'Active (Unknown)', 'WCI Supplier', 'WCI', 829, 'Big Mom Pirates', 'Longarm tribe.'),
(NULL, 'Streusen', 'Gourmet Knight', 1, 0, 'Active (Unknown)', 'Co-Founder', 'WCI', 868, 'Big Mom Pirates', 'Head Chef.'),
(NULL, 'Pound', NULL, 1, 0, 'Inactive (Civilian?)', 'Former Husband', 'WCI', 831, 'Big Mom Family', 'Lola/Chiffon''s father.'),
(NULL, 'Chiffon', NULL, 1, 0, 'Active', 'Bege''s Wife', 'WCI', 826, 'Fire Tank Pirates', 'Former Big Mom daughter.'),
(NULL, 'Lola', 'Proposer', 1, 24000000, 'Active', 'Rolling Pirates Captain', 'Thriller Bark', 450, 'Rolling Pirates', 'Big Mom''s runaway daughter.'),
(NULL, 'Risky Brothers', NULL, 1, 0, 'Active', 'Rolling Pirates', 'Thriller Bark', 450, 'Rolling Pirates', 'Zombies in Thriller Bark.'),
(NULL, 'Inazuma', NULL, 1, 0, 'Active (Unknown)', 'Revolutionary Deputy', 'Impel Down', 538, 'Revolutionary Army', 'Scissors Fruit.'),
(NULL, 'Emporio Ivankov', 'Okama King', 1, 0, 'Active (Unknown)', 'Revolutionary Commander (Grand Line)', 'Impel Down', 537, 'Revolutionary Army', 'Queen of Kamabakka.'),
(NULL, 'Koala', NULL, 1, 0, 'Active (Unknown)', 'Fishman Karate Instructor', 'Dressrosa', 731, 'Revolutionary Army', 'Former slave.'),
(NULL, 'Hack', NULL, 1, 0, 'Active (Unknown)', 'Fishman Karate Instructor', 'Dressrosa', 731, 'Revolutionary Army', 'Jimbei''s friend.'),
(NULL, 'Shiryu', 'OfThe Rain', 1, 0, 'Revoked (Impel Down)', 'Former Head Jailer', 'Impel Down', 538, 'Marines (Former)', 'Jailed for excessive violence.'),
(NULL, 'Shiryu', 'OfThe Rain', 2, 0, 'Active (Unknown)', 'Titanic Captain (2nd Ship)', 'Marineford', 576, 'Blackbeard Pirates', 'Clear-Clear Fruit user.'),
(NULL, 'Avalo Pizarro', 'Corrupt King', 1, 0, 'Active (Unknown)', 'Titanic Captain (4th Ship)', 'Marineford', 576, 'Blackbeard Pirates', 'Level 6 Escapee / Island Fruit.'),
(NULL, 'Catarina Devon', 'Crescent Moon Hunter', 1, 0, 'Active (Unknown)', 'Titanic Captain (6th Ship)', 'Marineford', 576, 'Blackbeard Pirates', 'Mythical Zoan (Nine Tailed Fox).'),
(NULL, 'Vasco Shot', 'Heavy Drinker', 1, 0, 'Active (Unknown)', 'Titanic Captain (8th Ship)', 'Marineford', 576, 'Blackbeard Pirates', 'Liquor-Liquor Fruit.'),
(NULL, 'Sanjuan Wolf', 'Colossal Battleship', 1, 0, 'Active (Unknown)', 'Titanic Captain (7th Ship)', 'Marineford', 576, 'Blackbeard Pirates', 'Giant Fruit / Largest Giant.'),
(NULL, 'Laffitte', 'Demon Sheriff', 1, 42200000, 'Active', 'Titanic Captain (5th Ship)', 'Jaya', 234, 'Blackbeard Pirates', 'Infiltrated Mary Geoise.'),
(NULL, 'Jesus Burgess', 'Champion', 1, 20000000, 'Active', 'Titanic Captain (1st Ship)', 'Jaya', 234, 'Blackbeard Pirates', 'Strong-Strong Fruit.'),
(NULL, 'Van Augur', 'Supersonic', 1, 64000000, 'Active', 'Titanic Captain (3rd Ship)', 'Jaya', 234, 'Blackbeard Pirates', 'Warp-Warp Fruit.'),
(NULL, 'Doc Q', 'Death God', 1, 72000000, 'Active', 'Titanic Captain (9th Ship)', 'Jaya', 234, 'Blackbeard Pirates', 'Sick-Sick Fruit.'),
(NULL, 'Kuzan', 'Aokiji', 1, 3000000000, 'Active (Cross Guild Estimate)', 'Titanic Captain (10th Ship)', 'Egghead', 1081, 'Blackbeard Pirates', 'Former Admiral.'),
(NULL, 'Stronger', NULL, 1, 0, 'Active', 'Horse', 'Jaya', 234, 'Blackbeard Pirates', 'Mythical Zoan (Pegasus).'),
(NULL, 'Miss Monday', NULL, 1, 0, 'Inactive', 'Baroque Works Agent', 'Whiskey Peak', 107, 'Baroque Works', 'Strength based.'),
(NULL, 'Mr. 9', NULL, 1, 0, 'Inactive', 'Baroque Works Agent', 'Whiskey Peak', 107, 'Baroque Works', 'Miss Wednesday''s partner.'),
(NULL, 'Mr. 7', 'Sniper', 1, 0, 'Inactive (Deceased?)', 'Baroque Works Agent', 'Alabasta', SBS, 'Baroque Works', 'Replaced by new Mr 7.'),
(NULL, 'Miss Father''s Day', NULL, 1, 0, 'Inactive', 'Baroque Works Agent', 'Alabasta', 204, 'Baroque Works', 'Frog gun user.'),
(NULL, 'Mr. 11', NULL, 1, 0, 'Inactive (Captured)', 'Baroque Works Agent', 'Alabasta', 160, 'Baroque Works', 'Captured by Smoker.'),
(NULL, 'Mr. 5', 'Gem', 1, 10000000, 'Active', 'Baroque Works Agent', 'Whiskey Peak', 110, 'Baroque Works', 'Bomb-Bomb Fruit.'),
(NULL, 'Miss All Sunday', 'Nico Robin', 1, 79000000, 'Active (Fake Name)', 'Baroque Works Vice President', 'Alabasta', 114, 'Baroque Works', 'Robin''s cover identity.'),
(NULL, 'Corgi', NULL, 1, 0, 'Inactive', 'Government Official', 'Water 7', 326, 'World Government', 'Tried to capture Robin.'),
(NULL, 'Spandam', NULL, 1, 0, 'Active', 'CP9 Chief / CP0', 'Enies Lobby', 358, 'CP9 / CP0', 'Weakest CP9 member.'),
(NULL, 'Rob Lucci', 'Massacre Weapon', 1, 0, 'Active (CP0)', 'CP9 Strongest / CP0', 'Water 7', 327, 'CP9 / CP0', 'Leopard Fruit.'),
(NULL, 'Kaku', 'Mountain Wind', 1, 0, 'Active (CP0)', 'CP9 / CP0', 'Water 7', 327, 'CP9 / CP0', 'Giraffe Fruit.'),
(NULL, 'Jabra', NULL, 1, 0, 'Inactive (CP0?)', 'CP9 Agent', 'Enies Lobby', 379, 'CP9', 'Wolf Fruit.'),
(NULL, 'Blueno', NULL, 1, 0, 'Active (CP0)', 'CP9 Agent', 'Water 7', 343, 'CP9 / CP0', 'Door-Door Fruit.'),
(NULL, 'Kumadori', NULL, 1, 0, 'Inactive (CP0?)', 'CP9 Agent', 'Enies Lobby', 379, 'CP9', 'Life Return.'),
(NULL, 'Fukuro', NULL, 1, 0, 'Inactive (CP0?)', 'CP9 Agent', 'Enies Lobby', 379, 'CP9', 'Zipper mouth.'),
(NULL, 'Kalifa', NULL, 1, 0, 'Active (CP0)', 'CP9 Agent', 'Water 7', 326, 'CP9 / CP0', 'Bubble Fruit.'),
(NULL, 'Nero', 'Sea Weasel', 1, 0, 'Inactive', 'CP9 New Recruit', 'Water 7', 363, 'CP9', 'Defeated by Franky on Sea Train.'),
(NULL, 'Wanze', 'Mad', 1, 0, 'Inactive', 'CP7 Chef', 'Water 7', 368, 'CP7', 'Ramen Kempo.'),
(NULL, 'T-Bone', NULL, 1, 0, 'Inactive (Marine)', 'Marine Captain (Pre-Cross Guild)', 'Water 7', 366, 'Marines', 'Known for hating crooked swordsmanship.'),
(NULL, 'Very Good', NULL, 1, 0, 'Active', 'Marine Captain', 'Enies Lobby', 426, 'Marines', 'Berry-Berry Fruit.'),
(NULL, 'Shu', NULL, 1, 0, 'Active', 'Marine Captain', 'Enies Lobby', 426, 'Marines', 'Rust-Rust Fruit (Destroyed Yubashiri).'),
(NULL, 'Sharinguru', NULL, 1, 0, 'Active', 'Marine Captain', 'Enies Lobby', 426, 'Marines', 'Wheel-Wheel Fruit.'),
(NULL, 'Strawberry', NULL, 1, 0, 'Active', 'Vice Admiral', 'Enies Lobby', 426, 'Marines', 'Long head.'),
(NULL, 'Yamakaji', NULL, 1, 0, 'Active', 'Vice Admiral', 'Enies Lobby', 426, 'Marines', 'Always smiling.'),
(NULL, 'Doberman', NULL, 1, 0, 'Active', 'Vice Admiral', 'Enies Lobby', 426, 'Marines', 'Scarred face.'),
(NULL, 'Onigumo', NULL, 1, 0, 'Active', 'Vice Admiral', 'Enies Lobby', 426, 'Marines', 'Spider-like hair.'),
(NULL, 'Momonga', NULL, 1, 0, 'Active', 'Vice Admiral', 'Enies Lobby', 426, 'Marines', 'Resisted Hancock.'),
(NULL, 'Bastille', 'Shark Cutter', 1, 0, 'Active', 'Vice Admiral', 'Dressrosa', 717, 'Marines', 'Defeated by Sabo.'),
(NULL, 'Maynard', 'Pursuer', 1, 0, 'Active', 'Vice Admiral', 'Dressrosa', 705, 'Marines', 'Infiltrated Colosseum as Capman.'),
(NULL, 'Smoker', 'White Hunter', 1, 0, 'Active', 'Vice Admiral', 'Loguetown', 97, 'Marines', 'Luffy''s persistent chaser.'),
(NULL, 'Tashigi', NULL, 1, 0, 'Active', 'Captain', 'Loguetown', 97, 'Marines', 'Sword nerd / Kuina lookalike.'),
(NULL, 'Hina', 'Black Cage', 1, 0, 'Active', 'Rear Admiral', 'Alabasta', 212, 'Marines', 'Cage-Cage Fruit.'),
(NULL, 'Fullbody', 'Double Ironfist', 1, 0, 'Demoted', 'Lieutenant', 'Baratie', 43, 'Marines', 'Demoted after Jango incident.'),
(NULL, 'Jango', 'Double Crosser', 2, 0, 'Active', 'Seaman Recruit', 'Alabasta', 212, 'Marines', 'Follows Hina.'),
(NULL, 'Morgan', 'Axe-Hand', 1, 0, 'Revoked (Fugitive)', 'Former Marine Captain', 'Romance Dawn', 3, 'None', 'Father of Helmeppo.'),
(NULL, 'Nezumi', NULL, 1, 0, 'Active (Corrupt)', 'Marine Captain', 'Arlong Park', 69, 'Marines', 'Took bribes from Arlong.'),
(NULL, 'Pudding Pudding', NULL, 1, 0, 'Inactive (Deceased?)', 'Commodore', 'Arlong Park', 77, 'Marines', 'Sunk by Arlong.'),
(NULL, 'Sentomaru', NULL, 1, 0, 'Active (Rebel?)', 'Science Unit Captain', 'Sabaody', 497, 'Marines / Egghead', 'Bodyguard of Vegapunk.'),
(NULL, 'Kong', NULL, 1, 0, 'Active', 'Commander-in-Chief', 'Water 7', 0, 'World Government', 'Former Fleet Admiral.'),
(NULL, 'Sengoku', 'The Buddha', 1, 3000000000, 'Active (Cross Guild Estimate)', 'Inspector General / Former Fleet Admiral', 'Jaya', 234, 'Marines', 'Mythical Zoan.'),
(NULL, 'Tsuru', 'Great Staff', 1, 1000000000, 'Active (Cross Guild Estimate)', 'Vice Admiral', 'Jaya', 234, 'Marines', 'Wash-Wash Fruit.'),
(NULL, 'Doll', NULL, 1, 0, 'Active', 'Vice Admiral', 'Egghead', 1061, 'Marines', 'G-14 Base Commander.'),
(NULL, 'Helmeppo', NULL, 1, 0, 'Active', 'Lieutenant Commander', 'Romance Dawn', 3, 'Marines', 'SWORD member.'),
(NULL, 'X Drake', 'Red Flag', 2, 0, 'Active', 'SWORD Captain', 'Sabaody', 498, 'Marines (SWORD)', 'Undercover Pirate.');

-- Attempt to link character_ids based on name matching
UPDATE op_bounties b SET character_id = c.id FROM op_characters c WHERE LOWER(b.character_name) = LOWER(c.name);
